<a href="https://colab.research.google.com/github/vlhsilvia/TRABAJOS-PRACTICOS/blob/Silviamaster/Copia_de_Geotaller_1__Extracci%C3%B3n_de_Datos_Geoespaciales_desde_la_Web_con_Python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Estructura de la Clase

##1. Introducción

1. ¿Qué es OpenStreetMap?
2. ¿Por qué usar APIs para obtener datos espaciales?
3. Explicación breve sobre GeoPandas y Folium para visualizar datos.

##2. Extracción de Datos Espaciales con OpenStreetMap API

1. Petición de datos de hospitales y cafeterías mediante requests a Overpass API.
2. Transformación de datos a un GeoDataFrame.

In [ ]:
import requests
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

In [ ]:
# Definir la consulta en Overpass API para obtener hospitales en Bogotá
overpass_url = "http://overpass-api.de/api/interpreter"
query_hospitales = """
[out:json];
area["name"="Bogotá"]->.searchArea;
(
  node["amenity"="hospital"](area.searchArea);
);
out center;
"""

# Hacer la petición a la API
response = requests.get(overpass_url, params={"data": query_hospitales})
data = response.json()

In [ ]:
print(data)

{'version': 0.6, 'generator': 'Overpass API 0.7.62.4 2390de5a', 'osm3s': {'timestamp_osm_base': '2025-02-12T00:30:20Z', 'timestamp_areas_base': '2024-12-31T00:49:33Z', 'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'}, 'elements': [{'type': 'node', 'id': 313416844, 'lat': 4.7118162, 'lon': -74.0307709, 'tags': {'addr:country': 'CO', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica El Bosque'}}, {'type': 'node', 'id': 370255315, 'lat': 4.6686029, 'lon': -74.0572938, 'tags': {'addr:street': 'Carrera 17', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Consultorios Country', 'source': 'Kaart Ground Survey 2017', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 392333383, 'lat': 4.6938583, 'lon': -74.0555222, 'tags': {'addr:city': 'Bogotá D.C.', 'addr:housenumber': '106-30', 'addr:postcode': '110111', 'addr:street': 'Avenida Carrera 45', 'amenity': 'hospital', 'emergency': 'yes', 'healthcare': 'hospital', 'name': 'Clínica Vascular Navarra'}}, {'type': 'node', 'id': 609071708, 'lat': 4.7044138, 'lon': -74.0410976, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica la Carolina'}}, {'type': 'node', 'id': 626874480, 'lat': 4.6906198, 'lon': -74.0571618, 'tags': {'amenity': 'hospital', 'emergency': 'no', 'healthcare': 'hospital', 'name': 'Clínica de Hipertensión Arterial y Cuidados Coronarios - CHACC', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 815175854, 'lat': 4.5924102, 'lon': -74.1068885, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica De Cancer De Bogotà'}}, {'type': 'node', 'id': 1193314956, 'lat': 4.7444966, 'lon': -74.0929713, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'NUEVA EPS'}}, {'type': 'node', 'id': 1317977132, 'lat': 4.6646389, 'lon': -74.0690447, 'tags': {'addr:street': 'Calle 72', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Totalfarma', 'source': 'Kaart Ground Survey 2017', 'wheelchair': 'no'}}, {'type': 'node', 'id': 1317977136, 'lat': 4.6721415, 'lon': -74.0788844, 'tags': {'addr:street': 'Avenida Calle 72', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Drogas Popular', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 1460310724, 'lat': 4.6728771, 'lon': -74.1420402, 'tags': {'amenity': 'hospital', 'emergency': 'no', 'healthcare': 'hospital', 'name': 'Hospital Fontibón'}}, {'type': 'node', 'id': 1626840072, 'lat': 4.6933194, 'lon': -74.0555373, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica Odontologica Jasban'}}, {'type': 'node', 'id': 1626844670, 'lat': 4.6976286, 'lon': -74.0503338, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'healthcare:speciality': 'orthopaedics;physiotherapy', 'name': 'Instituto de Ortopedia y Fractura'}}, {'type': 'node', 'id': 1626845467, 'lat': 4.692218, 'lon': -74.0511921, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'LaFam'}}, {'type': 'node', 'id': 1626846961, 'lat': 4.688106, 'lon': -74.0519818, 'tags': {'addr:street': 'Avenida Carrera 19', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica de la Sabana', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 1626852523, 'lat': 4.6846581, 'lon': -74.0571037, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Edificio Dalí - Clínica Estetica'}}, {'type': 'node', 'id': 1634634442, 'lat': 4.7339376, 'lon': -74.0448106, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clinicentro Cedro Bolivar'}}, {'type': 'node', 'id': 1642693961, 'lat': 4.6725699, 'lon': -74.0798987, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Puesto de salud San fernando'}}, {'type': 'node', 'id': 1661279380, 'lat': 4.6655942, 'lon': -74.0633017, 'tags': {'amenity': 'hospital', 'emergency': 'yes', 'healthcare': 'hospital', 'name': 'Hospital de Chapinero'}}, {'type': 'node', 'id': 1661458473, 'lat': 4.6811406, 'lon': -74.0485803, 'tags': {'amenity': 'hospital', 'emergency': 'no', 'healthcare': 'hospital', 'name': 'Sanitas CLL 95'}}, {'type': 'node', 'id': 2040979151, 'lat': 4.6012791, 'lon': -74.0669169, 'tags': {'amenity': 'hospital', 'contact:phone': '+57 601 3394949', 'description': 'Entrada por el edificio Ñh', 'designation': 'Centro médico', 'emergency': 'yes', 'healthcare': 'hospital', 'name': 'Centro Médico Uniandes', 'source': 'http://medicina.uniandes.edu.co'}}, {'type': 'node', 'id': 2315535486, 'lat': 4.6359714, 'lon': -74.0788582, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Salud Total'}}, {'type': 'node', 'id': 2744603396, 'lat': 4.7115933, 'lon': -74.0297221, 'tags': {'addr:city': 'Bogotá D.C.', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Doctora María Consuelo Carranza B. Cirujana Plástica'}}, {'type': 'node', 'id': 3419842531, 'lat': 4.5994773, 'lon': -74.132597, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Odontología'}}, {'type': 'node', 'id': 3419846101, 'lat': 4.625976, 'lon': -74.0670123, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Instituto Laboratorio Clinico'}}, {'type': 'node', 'id': 3544818813, 'lat': 4.6081771, 'lon': -74.0806549, 'tags': {'addr:city': 'Bogota', 'addr:street': 'Calle 16', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica San Francisco de Asis'}}, {'type': 'node', 'id': 4267146497, 'lat': 4.6521807, 'lon': -74.0520929, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'kekerkre'}}, {'type': 'node', 'id': 4313654837, 'lat': 4.6060582, 'lon': -74.0714421, 'tags': {'addr:housenumber': '19-63', 'addr:street': 'Carrera 7', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Drogueria Cafam'}}, {'type': 'node', 'id': 4832914021, 'lat': 4.6413289, 'lon': -74.0765505, 'tags': {'addr:housenumber': 'crra 27A 52-14', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Centro Odontologíco Fuerza Aérea', 'name:es': 'Centro Odontologíco Fuerza Aérea'}}, {'type': 'node', 'id': 5141968075, 'lat': 4.6967648, 'lon': -74.1125389, 'tags': {'addr:housenumber': '91A-65', 'addr:street': 'Calle 70A', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': "Veterinaria Animal's Help", 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 5141986169, 'lat': 4.6005189, 'lon': -74.1231707, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'clinica veterinaria animal zone'}}, {'type': 'node', 'id': 5320431171, 'lat': 4.7342116, 'lon': -74.0290195, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Cancha Microfutbol Altablanca'}}, {'type': 'node', 'id': 5364323335, 'lat': 4.6986477, 'lon': -74.0715624, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'healthcare:speciality': 'neurology;physiotherapy;neurophysology;occupational_therapy', 'name': 'Electrofisiatría SAS'}}, {'type': 'node', 'id': 5495053499, 'lat': 4.6982129, 'lon': -74.0899067, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'centro de salud'}}, {'type': 'node', 'id': 6501137717, 'lat': 4.6264463, 'lon': -74.0728484, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Medicos Sin Fronteras'}}, {'type': 'node', 'id': 6512097421, 'lat': 4.6242063, 'lon': -74.0709087, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'prosalud ocupacional'}}, {'type': 'node', 'id': 6520199856, 'lat': 4.6263631, 'lon': -74.0702896, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital'}}, {'type': 'node', 'id': 6655801203, 'lat': 4.670537, 'lon': -74.1531345, 'tags': {'addr:city': 'Bogota', 'addr:housenumber': '14-50', 'addr:street': 'Carrera 104', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Compensar EPS Fontibón', 'operator': 'Compensar EPS', 'operator:type': 'private', 'phone': '(1) 4441234'}}, {'type': 'node', 'id': 7600724117, 'lat': 4.5927759, 'lon': -74.0901629, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital'}}, {'type': 'node', 'id': 7921161245, 'lat': 4.6932049, 'lon': -74.0642817, 'tags': {'addr:city': 'Bogota', 'addr:housenumber': 'transversal 56', 'addr:postcode': '111111', 'addr:street': 'Calle 104B', 'amenity': 'hospital', 'healthcare': 'hospital', 'healthcare:speciality': 'veterinaria', 'name': 'hospital veterianrio'}}, {'type': 'node', 'id': 9060434038, 'lat': 4.6287176, 'lon': -74.0641532, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica San Ignacio', 'name:en': 'San Ignacio Clinic', 'name:es': 'Clínica San Ignacio'}}, {'type': 'node', 'id': 9598712460, 'lat': 4.663999, 'lon': -74.0659824, 'tags': {'amenity': 'hospital', 'contact:facebook': 'https://www.facebook.com/CruzRojaBogota/', 'contact:instagram': 'cruzrojabogota', 'contact:linkedin': 'https://www.linkedin.com/company/cruz-roja-colombiana-seccional-cundinamarca-y-bogot%C3%A1/', 'contact:twitter': '@cruzrojabogota', 'contact:whatsapp': '+57 317 3638993', 'contact:youtube': 'https://www.youtube.com/user/CRCSCB/videos', 'healthcare': 'hospital', 'name': 'Cruz Roja Colombiana - Seccional Cundinamarca Y Bogota', 'office': 'ngo', 'operator': 'Cruz Roja Colombiana', 'operator:wikidata': 'Q7178', 'operator:wikipedia': 'es:Cruz Roja', 'phone': '+57 601 7460909', 'website': 'https://www.cruzrojabogota.org.co/'}}, {'type': 'node', 'id': 9598712466, 'lat': 4.6725765, 'lon': -74.089479, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'SAMU 68', 'operator': 'Cruz Roja Colombiana Seccional Cundinamarca Y Bogota', 'operator:type': 'private_non_profit'}}, {'type': 'node', 'id': 9719571617, 'lat': 4.630924, 'lon': -74.1901353, 'tags': {'addr:housenumber': '89B-19', 'addr:street': 'Calle 57 Sur', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Centros de Atención Prioritaria en Salud Cabañas'}}, {'type': 'node', 'id': 9719586417, 'lat': 4.6093687, 'lon': -74.1857388, 'tags': {'addr:housenumber': '80H-44', 'addr:street': 'Calle 65 Sur', 'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Centros de Atención Prioritaria en Salud Bosa Centro'}}, {'type': 'node', 'id': 9736127250, 'lat': 4.7070462, 'lon': -74.0522841, 'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'Clínica Reina Sofia Colsánitas', 'operator': 'Colsánitas - Keralty', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 12366031345, 'lat': 4.5895932, 'lon': -74.0700723, 'tags': {'amenity': 'hospital', 'name': 'Hospital Jorge Eliecer Gaitán'}}]}

In [ ]:
#Visualicemos de una manera más organiada la información provista en data
import json
print(json.dumps(data, indent=2))

{
  "version": 0.6,
  "generator": "Overpass API 0.7.62.4 2390de5a",
  "osm3s": {
    "timestamp_osm_base": "2025-02-12T00:30:20Z",
    "timestamp_areas_base": "2024-12-31T00:49:33Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [
    {
      "type": "node",
      "id": 313416844,
      "lat": 4.7118162,
      "lon": -74.0307709,
      "tags": {
        "addr:country": "CO",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica El Bosque"
      }
    },
    {
      "type": "node",
      "id": 370255315,
      "lat": 4.6686029,
      "lon": -74.0572938,
      "tags": {
        "addr:street": "Carrera 17",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Consultorios Country",
        "source": "Kaart Ground Survey 2017",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 392333383,
      "lat": 4.6938583,
      "lon": -74.0555222,
      "tags": {
        "addr:city": "Bogot\u00e1 D.C.",
        "addr:housenumber": "106-30",
        "addr:postcode": "110111",
        "addr:street": "Avenida Carrera 45",
        "amenity": "hospital",
        "emergency": "yes",
        "healthcare": "hospital",
        "name": "Cl\u00ednica Vascular Navarra"
      }
    },
    {
      "type": "node",
      "id": 609071708,
      "lat": 4.7044138,
      "lon": -74.0410976,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica la Carolina"
      }
    },
    {
      "type": "node",
      "id": 626874480,
      "lat": 4.6906198,
      "lon": -74.0571618,
      "tags": {
        "amenity": "hospital",
        "emergency": "no",
        "healthcare": "hospital",
        "name": "Cl\u00ednica de Hipertensi\u00f3n Arterial y Cuidados Coronarios - CHACC",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 815175854,
      "lat": 4.5924102,
      "lon": -74.1068885,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica De Cancer De Bogot\u00e0"
      }
    },
    {
      "type": "node",
      "id": 1193314956,
      "lat": 4.7444966,
      "lon": -74.0929713,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "NUEVA EPS"
      }
    },
    {
      "type": "node",
      "id": 1317977132,
      "lat": 4.6646389,
      "lon": -74.0690447,
      "tags": {
        "addr:street": "Calle 72",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Totalfarma",
        "source": "Kaart Ground Survey 2017",
        "wheelchair": "no"
      }
    },
    {
      "type": "node",
      "id": 1317977136,
      "lat": 4.6721415,
      "lon": -74.0788844,
      "tags": {
        "addr:street": "Avenida Calle 72",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Drogas Popular",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 1460310724,
      "lat": 4.6728771,
      "lon": -74.1420402,
      "tags": {
        "amenity": "hospital",
        "emergency": "no",
        "healthcare": "hospital",
        "name": "Hospital Fontib\u00f3n"
      }
    },
    {
      "type": "node",
      "id": 1626840072,
      "lat": 4.6933194,
      "lon": -74.0555373,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica Odontologica Jasban"
      }
    },
    {
      "type": "node",
      "id": 1626844670,
      "lat": 4.6976286,
      "lon": -74.0503338,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "healthcare:speciality": "orthopaedics;physiotherapy",
        "name": "Instituto de Ortopedia y Fractura"
      }
    },
    {
      "type": "node",
      "id": 1626845467,
      "lat": 4.692218,
      "lon": -74.0511921,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "LaFam"
      }
    },
    {
      "type": "node",
      "id": 1626846961,
      "lat": 4.688106,
      "lon": -74.0519818,
      "tags": {
        "addr:street": "Avenida Carrera 19",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica de la Sabana",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 1626852523,
      "lat": 4.6846581,
      "lon": -74.0571037,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Edificio Dal\u00ed - Cl\u00ednica Estetica"
      }
    },
    {
      "type": "node",
      "id": 1634634442,
      "lat": 4.7339376,
      "lon": -74.0448106,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Clinicentro Cedro Bolivar"
      }
    },
    {
      "type": "node",
      "id": 1642693961,
      "lat": 4.6725699,
      "lon": -74.0798987,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Puesto de salud San fernando"
      }
    },
    {
      "type": "node",
      "id": 1661279380,
      "lat": 4.6655942,
      "lon": -74.0633017,
      "tags": {
        "amenity": "hospital",
        "emergency": "yes",
        "healthcare": "hospital",
        "name": "Hospital de Chapinero"
      }
    },
    {
      "type": "node",
      "id": 1661458473,
      "lat": 4.6811406,
      "lon": -74.0485803,
      "tags": {
        "amenity": "hospital",
        "emergency": "no",
        "healthcare": "hospital",
        "name": "Sanitas CLL 95"
      }
    },
    {
      "type": "node",
      "id": 2040979151,
      "lat": 4.6012791,
      "lon": -74.0669169,
      "tags": {
        "amenity": "hospital",
        "contact:phone": "+57 601 3394949",
        "description": "Entrada por el edificio \u00d1h",
        "designation": "Centro m\u00e9dico",
        "emergency": "yes",
        "healthcare": "hospital",
        "name": "Centro M\u00e9dico Uniandes",
        "source": "http://medicina.uniandes.edu.co"
      }
    },
    {
      "type": "node",
      "id": 2315535486,
      "lat": 4.6359714,
      "lon": -74.0788582,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Salud Total"
      }
    },
    {
      "type": "node",
      "id": 2744603396,
      "lat": 4.7115933,
      "lon": -74.0297221,
      "tags": {
        "addr:city": "Bogot\u00e1 D.C.",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Doctora Mar\u00eda Consuelo Carranza B. Cirujana Pl\u00e1stica"
      }
    },
    {
      "type": "node",
      "id": 3419842531,
      "lat": 4.5994773,
      "lon": -74.132597,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Odontolog\u00eda"
      }
    },
    {
      "type": "node",
      "id": 3419846101,
      "lat": 4.625976,
      "lon": -74.0670123,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Instituto Laboratorio Clinico"
      }
    },
    {
      "type": "node",
      "id": 3544818813,
      "lat": 4.6081771,
      "lon": -74.0806549,
      "tags": {
        "addr:city": "Bogota",
        "addr:street": "Calle 16",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica San Francisco de Asis"
      }
    },
    {
      "type": "node",
      "id": 4267146497,
      "lat": 4.6521807,
      "lon": -74.0520929,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "kekerkre"
      }
    },
    {
      "type": "node",
      "id": 4313654837,
      "lat": 4.6060582,
      "lon": -74.0714421,
      "tags": {
        "addr:housenumber": "19-63",
        "addr:street": "Carrera 7",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Drogueria Cafam"
      }
    },
    {
      "type": "node",
      "id": 4832914021,
      "lat": 4.6413289,
      "lon": -74.0765505,
      "tags": {
        "addr:housenumber": "crra 27A 52-14",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Centro Odontolog\u00edco Fuerza A\u00e9rea",
        "name:es": "Centro Odontolog\u00edco Fuerza A\u00e9rea"
      }
    },
    {
      "type": "node",
      "id": 5141968075,
      "lat": 4.6967648,
      "lon": -74.1125389,
      "tags": {
        "addr:housenumber": "91A-65",
        "addr:street": "Calle 70A",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Veterinaria Animal's Help",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 5141986169,
      "lat": 4.6005189,
      "lon": -74.1231707,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "clinica veterinaria animal zone"
      }
    },
    {
      "type": "node",
      "id": 5320431171,
      "lat": 4.7342116,
      "lon": -74.0290195,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cancha Microfutbol Altablanca"
      }
    },
    {
      "type": "node",
      "id": 5364323335,
      "lat": 4.6986477,
      "lon": -74.0715624,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "healthcare:speciality": "neurology;physiotherapy;neurophysology;occupational_therapy",
        "name": "Electrofisiatr\u00eda SAS"
      }
    },
    {
      "type": "node",
      "id": 5495053499,
      "lat": 4.6982129,
      "lon": -74.0899067,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "centro de salud"
      }
    },
    {
      "type": "node",
      "id": 6501137717,
      "lat": 4.6264463,
      "lon": -74.0728484,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Medicos Sin Fronteras"
      }
    },
    {
      "type": "node",
      "id": 6512097421,
      "lat": 4.6242063,
      "lon": -74.0709087,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "prosalud ocupacional"
      }
    },
    {
      "type": "node",
      "id": 6520199856,
      "lat": 4.6263631,
      "lon": -74.0702896,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital"
      }
    },
    {
      "type": "node",
      "id": 6655801203,
      "lat": 4.670537,
      "lon": -74.1531345,
      "tags": {
        "addr:city": "Bogota",
        "addr:housenumber": "14-50",
        "addr:street": "Carrera 104",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Compensar EPS Fontib\u00f3n",
        "operator": "Compensar EPS",
        "operator:type": "private",
        "phone": "(1) 4441234"
      }
    },
    {
      "type": "node",
      "id": 7600724117,
      "lat": 4.5927759,
      "lon": -74.0901629,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital"
      }
    },
    {
      "type": "node",
      "id": 7921161245,
      "lat": 4.6932049,
      "lon": -74.0642817,
      "tags": {
        "addr:city": "Bogota",
        "addr:housenumber": "transversal 56",
        "addr:postcode": "111111",
        "addr:street": "Calle 104B",
        "amenity": "hospital",
        "healthcare": "hospital",
        "healthcare:speciality": "veterinaria",
        "name": "hospital veterianrio"
      }
    },
    {
      "type": "node",
      "id": 9060434038,
      "lat": 4.6287176,
      "lon": -74.0641532,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica San Ignacio",
        "name:en": "San Ignacio Clinic",
        "name:es": "Cl\u00ednica San Ignacio"
      }
    },
    {
      "type": "node",
      "id": 9598712460,
      "lat": 4.663999,
      "lon": -74.0659824,
      "tags": {
        "amenity": "hospital",
        "contact:facebook": "https://www.facebook.com/CruzRojaBogota/",
        "contact:instagram": "cruzrojabogota",
        "contact:linkedin": "https://www.linkedin.com/company/cruz-roja-colombiana-seccional-cundinamarca-y-bogot%C3%A1/",
        "contact:twitter": "@cruzrojabogota",
        "contact:whatsapp": "+57 317 3638993",
        "contact:youtube": "https://www.youtube.com/user/CRCSCB/videos",
        "healthcare": "hospital",
        "name": "Cruz Roja Colombiana - Seccional Cundinamarca Y Bogota",
        "office": "ngo",
        "operator": "Cruz Roja Colombiana",
        "operator:wikidata": "Q7178",
        "operator:wikipedia": "es:Cruz Roja",
        "phone": "+57 601 7460909",
        "website": "https://www.cruzrojabogota.org.co/"
      }
    },
    {
      "type": "node",
      "id": 9598712466,
      "lat": 4.6725765,
      "lon": -74.089479,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "SAMU 68",
        "operator": "Cruz Roja Colombiana Seccional Cundinamarca Y Bogota",
        "operator:type": "private_non_profit"
      }
    },
    {
      "type": "node",
      "id": 9719571617,
      "lat": 4.630924,
      "lon": -74.1901353,
      "tags": {
        "addr:housenumber": "89B-19",
        "addr:street": "Calle 57 Sur",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Centros de Atenci\u00f3n Prioritaria en Salud Caba\u00f1as"
      }
    },
    {
      "type": "node",
      "id": 9719586417,
      "lat": 4.6093687,
      "lon": -74.1857388,
      "tags": {
        "addr:housenumber": "80H-44",
        "addr:street": "Calle 65 Sur",
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Centros de Atenci\u00f3n Prioritaria en Salud Bosa Centro"
      }
    },
    {
      "type": "node",
      "id": 9736127250,
      "lat": 4.7070462,
      "lon": -74.0522841,
      "tags": {
        "amenity": "hospital",
        "healthcare": "hospital",
        "name": "Cl\u00ednica Reina Sofia Cols\u00e1nitas",
        "operator": "Cols\u00e1nitas - Keralty",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 12366031345,
      "lat": 4.5895932,
      "lon": -74.0700723,
      "tags": {
        "amenity": "hospital",
        "name": "Hospital Jorge Eliecer Gait\u00e1n"
      }
    }
  ]
}

Qué hay en *data["elements"]*?

In [ ]:
data["elements"]

[{'type': 'node',
  'id': 313416844,
  'lat': 4.7118162,
  'lon': -74.0307709,
  'tags': {'addr:country': 'CO',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica El Bosque'}},
 {'type': 'node',
  'id': 370255315,
  'lat': 4.6686029,
  'lon': -74.0572938,
  'tags': {'addr:street': 'Carrera 17',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Consultorios Country',
   'source': 'Kaart Ground Survey 2017',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 392333383,
  'lat': 4.6938583,
  'lon': -74.0555222,
  'tags': {'addr:city': 'Bogotá D.C.',
   'addr:housenumber': '106-30',
   'addr:postcode': '110111',
   'addr:street': 'Avenida Carrera 45',
   'amenity': 'hospital',
   'emergency': 'yes',
   'healthcare': 'hospital',
   'name': 'Clínica Vascular Navarra'}},
 {'type': 'node',
  'id': 609071708,
  'lat': 4.7044138,
  'lon': -74.0410976,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica la Carolina'}},
 {'type': 'node',
  'id': 626874480,
  'lat': 4.6906198,
  'lon': -74.0571618,
  'tags': {'amenity': 'hospital',
   'emergency': 'no',
   'healthcare': 'hospital',
   'name': 'Clínica de Hipertensión Arterial y Cuidados Coronarios - CHACC',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 815175854,
  'lat': 4.5924102,
  'lon': -74.1068885,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica De Cancer De Bogotà'}},
 {'type': 'node',
  'id': 1193314956,
  'lat': 4.7444966,
  'lon': -74.0929713,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'NUEVA EPS'}},
 {'type': 'node',
  'id': 1317977132,
  'lat': 4.6646389,
  'lon': -74.0690447,
  'tags': {'addr:street': 'Calle 72',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Totalfarma',
   'source': 'Kaart Ground Survey 2017',
   'wheelchair': 'no'}},
 {'type': 'node',
  'id': 1317977136,
  'lat': 4.6721415,
  'lon': -74.0788844,
  'tags': {'addr:street': 'Avenida Calle 72',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Drogas Popular',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 1460310724,
  'lat': 4.6728771,
  'lon': -74.1420402,
  'tags': {'amenity': 'hospital',
   'emergency': 'no',
   'healthcare': 'hospital',
   'name': 'Hospital Fontibón'}},
 {'type': 'node',
  'id': 1626840072,
  'lat': 4.6933194,
  'lon': -74.0555373,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica Odontologica Jasban'}},
 {'type': 'node',
  'id': 1626844670,
  'lat': 4.6976286,
  'lon': -74.0503338,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'healthcare:speciality': 'orthopaedics;physiotherapy',
   'name': 'Instituto de Ortopedia y Fractura'}},
 {'type': 'node',
  'id': 1626845467,
  'lat': 4.692218,
  'lon': -74.0511921,
  'tags': {'amenity': 'hospital', 'healthcare': 'hospital', 'name': 'LaFam'}},
 {'type': 'node',
  'id': 1626846961,
  'lat': 4.688106,
  'lon': -74.0519818,
  'tags': {'addr:street': 'Avenida Carrera 19',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica de la Sabana',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 1626852523,
  'lat': 4.6846581,
  'lon': -74.0571037,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Edificio Dalí - Clínica Estetica'}},
 {'type': 'node',
  'id': 1634634442,
  'lat': 4.7339376,
  'lon': -74.0448106,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clinicentro Cedro Bolivar'}},
 {'type': 'node',
  'id': 1642693961,
  'lat': 4.6725699,
  'lon': -74.0798987,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Puesto de salud San fernando'}},
 {'type': 'node',
  'id': 1661279380,
  'lat': 4.6655942,
  'lon': -74.0633017,
  'tags': {'amenity': 'hospital',
   'emergency': 'yes',
   'healthcare': 'hospital',
   'name': 'Hospital de Chapinero'}},
 {'type': 'node',
  'id': 1661458473,
  'lat': 4.6811406,
  'lon': -74.0485803,
  'tags': {'amenity': 'hospital',
   'emergency': 'no',
   'healthcare': 'hospital',
   'name': 'Sanitas CLL 95'}},
 {'type': 'node',
  'id': 2040979151,
  'lat': 4.6012791,
  'lon': -74.0669169,
  'tags': {'amenity': 'hospital',
   'contact:phone': '+57 601 3394949',
   'description': 'Entrada por el edificio Ñh',
   'designation': 'Centro médico',
   'emergency': 'yes',
   'healthcare': 'hospital',
   'name': 'Centro Médico Uniandes',
   'source': 'http://medicina.uniandes.edu.co'}},
 {'type': 'node',
  'id': 2315535486,
  'lat': 4.6359714,
  'lon': -74.0788582,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Salud Total'}},
 {'type': 'node',
  'id': 2744603396,
  'lat': 4.7115933,
  'lon': -74.0297221,
  'tags': {'addr:city': 'Bogotá D.C.',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Doctora María Consuelo Carranza B. Cirujana Plástica'}},
 {'type': 'node',
  'id': 3419842531,
  'lat': 4.5994773,
  'lon': -74.132597,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Odontología'}},
 {'type': 'node',
  'id': 3419846101,
  'lat': 4.625976,
  'lon': -74.0670123,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Instituto Laboratorio Clinico'}},
 {'type': 'node',
  'id': 3544818813,
  'lat': 4.6081771,
  'lon': -74.0806549,
  'tags': {'addr:city': 'Bogota',
   'addr:street': 'Calle 16',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica San Francisco de Asis'}},
 {'type': 'node',
  'id': 4267146497,
  'lat': 4.6521807,
  'lon': -74.0520929,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'kekerkre'}},
 {'type': 'node',
  'id': 4313654837,
  'lat': 4.6060582,
  'lon': -74.0714421,
  'tags': {'addr:housenumber': '19-63',
   'addr:street': 'Carrera 7',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Drogueria Cafam'}},
 {'type': 'node',
  'id': 4832914021,
  'lat': 4.6413289,
  'lon': -74.0765505,
  'tags': {'addr:housenumber': 'crra 27A 52-14',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Centro Odontologíco Fuerza Aérea',
   'name:es': 'Centro Odontologíco Fuerza Aérea'}},
 {'type': 'node',
  'id': 5141968075,
  'lat': 4.6967648,
  'lon': -74.1125389,
  'tags': {'addr:housenumber': '91A-65',
   'addr:street': 'Calle 70A',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': "Veterinaria Animal's Help",
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 5141986169,
  'lat': 4.6005189,
  'lon': -74.1231707,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'clinica veterinaria animal zone'}},
 {'type': 'node',
  'id': 5320431171,
  'lat': 4.7342116,
  'lon': -74.0290195,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Cancha Microfutbol Altablanca'}},
 {'type': 'node',
  'id': 5364323335,
  'lat': 4.6986477,
  'lon': -74.0715624,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'healthcare:speciality': 'neurology;physiotherapy;neurophysology;occupational_therapy',
   'name': 'Electrofisiatría SAS'}},
 {'type': 'node',
  'id': 5495053499,
  'lat': 4.6982129,
  'lon': -74.0899067,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'centro de salud'}},
 {'type': 'node',
  'id': 6501137717,
  'lat': 4.6264463,
  'lon': -74.0728484,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Medicos Sin Fronteras'}},
 {'type': 'node',
  'id': 6512097421,
  'lat': 4.6242063,
  'lon': -74.0709087,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'prosalud ocupacional'}},
 {'type': 'node',
  'id': 6520199856,
  'lat': 4.6263631,
  'lon': -74.0702896,
  'tags': {'amenity': 'hospital', 'healthcare': 'hospital'}},
 {'type': 'node',
  'id': 6655801203,
  'lat': 4.670537,
  'lon': -74.1531345,
  'tags': {'addr:city': 'Bogota',
   'addr:housenumber': '14-50',
   'addr:street': 'Carrera 104',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Compensar EPS Fontibón',
   'operator': 'Compensar EPS',
   'operator:type': 'private',
   'phone': '(1) 4441234'}},
 {'type': 'node',
  'id': 7600724117,
  'lat': 4.5927759,
  'lon': -74.0901629,
  'tags': {'amenity': 'hospital', 'healthcare': 'hospital'}},
 {'type': 'node',
  'id': 7921161245,
  'lat': 4.6932049,
  'lon': -74.0642817,
  'tags': {'addr:city': 'Bogota',
   'addr:housenumber': 'transversal 56',
   'addr:postcode': '111111',
   'addr:street': 'Calle 104B',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'healthcare:speciality': 'veterinaria',
   'name': 'hospital veterianrio'}},
 {'type': 'node',
  'id': 9060434038,
  'lat': 4.6287176,
  'lon': -74.0641532,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica San Ignacio',
   'name:en': 'San Ignacio Clinic',
   'name:es': 'Clínica San Ignacio'}},
 {'type': 'node',
  'id': 9598712460,
  'lat': 4.663999,
  'lon': -74.0659824,
  'tags': {'amenity': 'hospital',
   'contact:facebook': 'https://www.facebook.com/CruzRojaBogota/',
   'contact:instagram': 'cruzrojabogota',
   'contact:linkedin': 'https://www.linkedin.com/company/cruz-roja-colombiana-seccional-cundinamarca-y-bogot%C3%A1/',
   'contact:twitter': '@cruzrojabogota',
   'contact:whatsapp': '+57 317 3638993',
   'contact:youtube': 'https://www.youtube.com/user/CRCSCB/videos',
   'healthcare': 'hospital',
   'name': 'Cruz Roja Colombiana - Seccional Cundinamarca Y Bogota',
   'office': 'ngo',
   'operator': 'Cruz Roja Colombiana',
   'operator:wikidata': 'Q7178',
   'operator:wikipedia': 'es:Cruz Roja',
   'phone': '+57 601 7460909',
   'website': 'https://www.cruzrojabogota.org.co/'}},
 {'type': 'node',
  'id': 9598712466,
  'lat': 4.6725765,
  'lon': -74.089479,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'SAMU 68',
   'operator': 'Cruz Roja Colombiana Seccional Cundinamarca Y Bogota',
   'operator:type': 'private_non_profit'}},
 {'type': 'node',
  'id': 9719571617,
  'lat': 4.630924,
  'lon': -74.1901353,
  'tags': {'addr:housenumber': '89B-19',
   'addr:street': 'Calle 57 Sur',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Centros de Atención Prioritaria en Salud Cabañas'}},
 {'type': 'node',
  'id': 9719586417,
  'lat': 4.6093687,
  'lon': -74.1857388,
  'tags': {'addr:housenumber': '80H-44',
   'addr:street': 'Calle 65 Sur',
   'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Centros de Atención Prioritaria en Salud Bosa Centro'}},
 {'type': 'node',
  'id': 9736127250,
  'lat': 4.7070462,
  'lon': -74.0522841,
  'tags': {'amenity': 'hospital',
   'healthcare': 'hospital',
   'name': 'Clínica Reina Sofia Colsánitas',
   'operator': 'Colsánitas - Keralty',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 12366031345,
  'lat': 4.5895932,
  'lon': -74.0700723,
  'tags': {'amenity': 'hospital', 'name': 'Hospital Jorge Eliecer Gaitán'}}]

In [ ]:
# Extraer información y convertirla en DataFrame
elements = data["elements"]
hospitales = []
for element in elements:
    if "lat" in element and "lon" in element:
        hospitales.append({
            "name": element["tags"].get("name", "Desconocido"),
            "lat": element["lat"],
            "lon": element["lon"]
        })

In [ ]:
print(hospitales)

[{'name': 'Clínica El Bosque', 'lat': 4.7118162, 'lon': -74.0307709}, {'name': 'Consultorios Country', 'lat': 4.6686029, 'lon': -74.0572938}, {'name': 'Clínica Vascular Navarra', 'lat': 4.6938583, 'lon': -74.0555222}, {'name': 'Clínica la Carolina', 'lat': 4.7044138, 'lon': -74.0410976}, {'name': 'Clínica de Hipertensión Arterial y Cuidados Coronarios - CHACC', 'lat': 4.6906198, 'lon': -74.0571618}, {'name': 'Clínica De Cancer De Bogotà', 'lat': 4.5924102, 'lon': -74.1068885}, {'name': 'NUEVA EPS', 'lat': 4.7444966, 'lon': -74.0929713}, {'name': 'Totalfarma', 'lat': 4.6646389, 'lon': -74.0690447}, {'name': 'Drogas Popular', 'lat': 4.6721415, 'lon': -74.0788844}, {'name': 'Hospital Fontibón', 'lat': 4.6728771, 'lon': -74.1420402}, {'name': 'Clínica Odontologica Jasban', 'lat': 4.6933194, 'lon': -74.0555373}, {'name': 'Instituto de Ortopedia y Fractura', 'lat': 4.6976286, 'lon': -74.0503338}, {'name': 'LaFam', 'lat': 4.692218, 'lon': -74.0511921}, {'name': 'Clínica de la Sabana', 'lat': 4.688106, 'lon': -74.0519818}, {'name': 'Edificio Dalí - Clínica Estetica', 'lat': 4.6846581, 'lon': -74.0571037}, {'name': 'Clinicentro Cedro Bolivar', 'lat': 4.7339376, 'lon': -74.0448106}, {'name': 'Puesto de salud San fernando', 'lat': 4.6725699, 'lon': -74.0798987}, {'name': 'Hospital de Chapinero', 'lat': 4.6655942, 'lon': -74.0633017}, {'name': 'Sanitas CLL 95', 'lat': 4.6811406, 'lon': -74.0485803}, {'name': 'Centro Médico Uniandes', 'lat': 4.6012791, 'lon': -74.0669169}, {'name': 'Salud Total', 'lat': 4.6359714, 'lon': -74.0788582}, {'name': 'Doctora María Consuelo Carranza B. Cirujana Plástica', 'lat': 4.7115933, 'lon': -74.0297221}, {'name': 'Odontología', 'lat': 4.5994773, 'lon': -74.132597}, {'name': 'Instituto Laboratorio Clinico', 'lat': 4.625976, 'lon': -74.0670123}, {'name': 'Clínica San Francisco de Asis', 'lat': 4.6081771, 'lon': -74.0806549}, {'name': 'kekerkre', 'lat': 4.6521807, 'lon': -74.0520929}, {'name': 'Drogueria Cafam', 'lat': 4.6060582, 'lon': -74.0714421}, {'name': 'Centro Odontologíco Fuerza Aérea', 'lat': 4.6413289, 'lon': -74.0765505}, {'name': "Veterinaria Animal's Help", 'lat': 4.6967648, 'lon': -74.1125389}, {'name': 'clinica veterinaria animal zone', 'lat': 4.6005189, 'lon': -74.1231707}, {'name': 'Cancha Microfutbol Altablanca', 'lat': 4.7342116, 'lon': -74.0290195}, {'name': 'Electrofisiatría SAS', 'lat': 4.6986477, 'lon': -74.0715624}, {'name': 'centro de salud', 'lat': 4.6982129, 'lon': -74.0899067}, {'name': 'Medicos Sin Fronteras', 'lat': 4.6264463, 'lon': -74.0728484}, {'name': 'prosalud ocupacional', 'lat': 4.6242063, 'lon': -74.0709087}, {'name': 'Desconocido', 'lat': 4.6263631, 'lon': -74.0702896}, {'name': 'Compensar EPS Fontibón', 'lat': 4.670537, 'lon': -74.1531345}, {'name': 'Desconocido', 'lat': 4.5927759, 'lon': -74.0901629}, {'name': 'hospital veterianrio', 'lat': 4.6932049, 'lon': -74.0642817}, {'name': 'Clínica San Ignacio', 'lat': 4.6287176, 'lon': -74.0641532}, {'name': 'Cruz Roja Colombiana - Seccional Cundinamarca Y Bogota', 'lat': 4.663999, 'lon': -74.0659824}, {'name': 'SAMU 68', 'lat': 4.6725765, 'lon': -74.089479}, {'name': 'Centros de Atención Prioritaria en Salud Cabañas', 'lat': 4.630924, 'lon': -74.1901353}, {'name': 'Centros de Atención Prioritaria en Salud Bosa Centro', 'lat': 4.6093687, 'lon': -74.1857388}, {'name': 'Clínica Reina Sofia Colsánitas', 'lat': 4.7070462, 'lon': -74.0522841}, {'name': 'Hospital Jorge Eliecer Gaitán', 'lat': 4.5895932, 'lon': -74.0700723}]

In [ ]:
# Convertir a GeoDataFrame
df_hospitales = pd.DataFrame(hospitales)
print(df_hospitales)

                                                 name       lat        lon
0                                   Clínica El Bosque  4.711816 -74.030771
1                                Consultorios Country  4.668603 -74.057294
2                            Clínica Vascular Navarra  4.693858 -74.055522
3                                 Clínica la Carolina  4.704414 -74.041098
4   Clínica de Hipertensión Arterial y Cuidados Co...  4.690620 -74.057162
5                         Clínica De Cancer De Bogotà  4.592410 -74.106888
6                                           NUEVA EPS  4.744497 -74.092971
7                                          Totalfarma  4.664639 -74.069045
8                                      Drogas Popular  4.672142 -74.078884
9                                   Hospital Fontibón  4.672877 -74.142040
10                        Clínica Odontologica Jasban  4.693319 -74.055537
11                  Instituto de Ortopedia y Fractura  4.697629 -74.050334
12                                              LaFam  4.692218 -74.051192
13                               Clínica de la Sabana  4.688106 -74.051982
14                   Edificio Dalí - Clínica Estetica  4.684658 -74.057104
15                          Clinicentro Cedro Bolivar  4.733938 -74.044811
16                       Puesto de salud San fernando  4.672570 -74.079899
17                              Hospital de Chapinero  4.665594 -74.063302
18                                     Sanitas CLL 95  4.681141 -74.048580
19                             Centro Médico Uniandes  4.601279 -74.066917
20                                        Salud Total  4.635971 -74.078858
21  Doctora María Consuelo Carranza B. Cirujana Pl...  4.711593 -74.029722
22                                        Odontología  4.599477 -74.132597
23                      Instituto Laboratorio Clinico  4.625976 -74.067012
24                      Clínica San Francisco de Asis  4.608177 -74.080655
25                                           kekerkre  4.652181 -74.052093
26                                    Drogueria Cafam  4.606058 -74.071442
27                   Centro Odontologíco Fuerza Aérea  4.641329 -74.076550
28                          Veterinaria Animal's Help  4.696765 -74.112539
29                    clinica veterinaria animal zone  4.600519 -74.123171
30                      Cancha Microfutbol Altablanca  4.734212 -74.029020
31                               Electrofisiatría SAS  4.698648 -74.071562
32                                    centro de salud  4.698213 -74.089907
33                              Medicos Sin Fronteras  4.626446 -74.072848
34                               prosalud ocupacional  4.624206 -74.070909
35                                        Desconocido  4.626363 -74.070290
36                             Compensar EPS Fontibón  4.670537 -74.153134
37                                        Desconocido  4.592776 -74.090163
38                               hospital veterianrio  4.693205 -74.064282
39                                Clínica San Ignacio  4.628718 -74.064153
40  Cruz Roja Colombiana - Seccional Cundinamarca ...  4.663999 -74.065982
41                                            SAMU 68  4.672576 -74.089479
42   Centros de Atención Prioritaria en Salud Cabañas  4.630924 -74.190135
43  Centros de Atención Prioritaria en Salud Bosa ...  4.609369 -74.185739
44                     Clínica Reina Sofia Colsánitas  4.707046 -74.052284
45                      Hospital Jorge Eliecer Gaitán  4.589593 -74.070072

In [ ]:
gdf_hospitales = gpd.GeoDataFrame(df_hospitales,
                                  geometry=gpd.points_from_xy(df_hospitales.lon, df_hospitales.lat),
                                  crs="EPSG:4326")

In [ ]:
# Mostrar los primeros registros
gdf_hospitales.tail()

,name,lat,lon,geometry
41,SAMU 68,4.672576,-74.089479,POINT (-74.08948 4.67258)
42,Centros de Atención Prioritaria en Salud Cabañas,4.630924,-74.190135,POINT (-74.19014 4.63092)
43,Centros de Atención Prioritaria en Salud Bosa ...,4.609369,-74.185739,POINT (-74.18574 4.60937)
44,Clínica Reina Sofia Colsánitas,4.707046,-74.052284,POINT (-74.05228 4.70705)
45,Hospital Jorge Eliecer Gaitán,4.589593,-74.070072,POINT (-74.07007 4.58959)

**Qué hemos hecho hasta aquí?**:

* Se usa Overpass API para extraer hospitales en Bogotá.
* Se transforma la respuesta JSON en un GeoDataFrame con coordenadas.

##3. Visualización de Datos en un Mapa Interactivo

1. Uso de Folium para visualizar hospitales en un mapa interactivo.
2. Creación de capas de diferentes categorías (hospitales vs. cafeterías).

In [ ]:
import folium

In [ ]:
# Crear mapa base centrado en Bogotá
m = folium.Map(location=[4.7110, -74.0721], zoom_start=12)
m

In [ ]:
# Agregar hospitales al mapa
for idx, row in gdf_hospitales.iterrows():
    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=row["name"],
        icon=folium.Icon(color="red", icon="plus-sign"),
    ).add_to(m)

# Mostrar mapa
m

 Explicación del Código:

1. Se usa Folium para visualizar los hospitales en Bogotá.
2. Se agregan marcadores rojos (icon="plus-sign") en la ubicación de cada hospital.

##4. Integración de Múltiples Capas: Hospitales y Cafeterías (10 min)

* Se repite el proceso anterior para cafeterías.
*  Se combinan ambos datasets en un solo mapa.

In [ ]:
# Definir la consulta para obtener cafeterías en Bogotá
query_cafeterias = """
[out:json];
area["name"="Bogotá"]->.searchArea;
(
  node["amenity"="cafe"](area.searchArea);
);
out center;
"""

# Hacer la petición y extraer datos
response_cafes = requests.get(overpass_url, params={"data": query_cafeterias})
response_cafes

In [ ]:
data_cafes = response_cafes.json()
print(data_cafes)

{'version': 0.6, 'generator': 'Overpass API 0.7.62.4 2390de5a', 'osm3s': {'timestamp_osm_base': '2025-02-12T00:30:20Z', 'timestamp_areas_base': '2024-12-31T00:49:33Z', 'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'}, 'elements': [{'type': 'node', 'id': 265501503, 'lat': 4.6396774, 'lon': -74.0630225, 'tags': {'amenity': 'cafe', 'brand': 'Juan Valdez Café', 'brand:wikidata': 'Q6301102', 'brand:wikipedia': 'en:Juan Valdez Café', 'cuisine': 'coffee_shop', 'name': 'Juan Valdez Café', 'name:es': 'Juan Valdez Café', 'shop': 'coffee', 'takeaway': 'yes', 'website': 'https://juanvaldez.com/'}}, {'type': 'node', 'id': 265501535, 'lat': 4.6402868, 'lon': -74.0628995, 'tags': {'addr:street': 'Avenida Carrera 7', 'amenity': 'cafe', 'name': 'La Cafeteria', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 340429454, 'lat': 4.6761001, 'lon': -74.0475614, 'tags': {'amenity': 'cafe', 'brand': 'Juan Valdez Café', 'brand:wikidata': 'Q6301102', 'brand:wikipedia': 'en:Juan Valdez Café', 'cuisine': 'coffee_shop', 'name': 'Juan Valdez Café', 'name:es': 'Juan Valdez Café', 'opening_hours': 'Mo-Su 07:00-22:00', 'shop': 'coffee', 'takeaway': 'yes', 'website': 'https://juanvaldez.com/', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 368176844, 'lat': 4.6504734, 'lon': -74.0917405, 'tags': {'amenity': 'cafe', 'name': 'Salon de Té F&W'}}, {'type': 'node', 'id': 405236743, 'lat': 4.7070904, 'lon': -74.0581185, 'tags': {'amenity': 'cafe', 'brand': "Pan Pa' Ya!", 'brand:wikidata': 'Q131744932', 'level': '0', 'name': "Pan Pa' Ya!", 'payment:cards': 'yes', 'payment:cash': 'yes', 'service:electricity': 'no', 'shop': 'bakery', 'smoking': 'no', 'wheelchair': 'yes'}}, {'type': 'node', 'id': 460405530, 'lat': 4.6580768, 'lon': -74.1118237, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 485363102, 'lat': 4.6824213, 'lon': -74.0488925, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'name': 'Café OMA', 'takeaway': 'yes', 'website': 'https://www.cafeoma.com/', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 485536579, 'lat': 4.7267619, 'lon': -74.0357369, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 494767144, 'lat': 4.7614606, 'lon': -74.0437824, 'tags': {'amenity': 'cafe', 'name': 'El marinero'}}, {'type': 'node', 'id': 499109158, 'lat': 4.7717566, 'lon': -74.0423748, 'tags': {'amenity': 'cafe', 'name': 'On the run'}}, {'type': 'node', 'id': 501789966, 'lat': 4.6668322, 'lon': -74.0525611, 'tags': {'amenity': 'cafe', 'brand': 'Juan Valdez Café', 'brand:wikidata': 'Q6301102', 'brand:wikipedia': 'en:Juan Valdez Café', 'cuisine': 'coffee_shop', 'name': 'Juan Valdez Café', 'name:es': 'Juan Valdez Café', 'shop': 'coffee', 'takeaway': 'yes', 'website': 'https://juanvaldez.com/', 'wheelchair': 'no'}}, {'type': 'node', 'id': 505075470, 'lat': 4.6979174, 'lon': -74.0691586, 'tags': {'addr:street': 'Avenida Suba', 'amenity': 'cafe', 'name': 'Autopan', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 506310009, 'lat': 4.7387233, 'lon': -74.0443946, 'tags': {'amenity': 'cafe', 'name': 'Cafe internet'}}, {'type': 'node', 'id': 506542813, 'lat': 4.7290096, 'lon': -74.0408665, 'tags': {'addr:street': 'Avenida Cedritos', 'amenity': 'cafe', 'brand': "Pan Pa' Ya!", 'brand:wikidata': 'Q131744932', 'name': "Pan Pa' Ya!", 'shop': 'bakery', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 517123861, 'lat': 4.6910866, 'lon': -74.1003074, 'tags': {'amenity': 'cafe', 'name': 'Festytortas'}}, {'type': 'node', 'id': 529748669, 'lat': 4.6430295, 'lon': -74.101606, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 595598570, 'lat': 4.6703265, 'lon': -74.1062994, 'tags': {'amenity': 'cafe', 'name': 'Pasteleria Santander'}}, {'type': 'node', 'id': 600238725, 'lat': 4.701068, 'lon': -74.115428, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 601254785, 'lat': 4.6425553, 'lon': -74.1348505, 'tags': {'addr:city': 'Kennedy', 'addr:street': 'Carrera 72A', 'amenity': 'cafe', 'name': 'Meridianos Pan y Cafe', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 601255096, 'lat': 4.6577458, 'lon': -74.1182451, 'tags': {'amenity': 'cafe', 'name': 'Pan Suizo'}}, {'type': 'node', 'id': 605667595, 'lat': 4.6503058, 'lon': -74.0870628, 'tags': {'amenity': 'cafe', 'name': 'Picos y Cafe'}}, {'type': 'node', 'id': 614660111, 'lat': 4.7281189, 'lon': -74.0648271, 'tags': {'amenity': 'cafe', 'name': 'Juan Valdés'}}, {'type': 'node', 'id': 616522538, 'lat': 4.7109718, 'lon': -74.140064, 'tags': {'addr:street': 'Calle 64', 'amenity': 'cafe', 'name': 'Monserrate', 'shop': 'bakery', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 662221657, 'lat': 4.6836004, 'lon': -74.0804715, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'name': 'Café OMA', 'takeaway': 'yes', 'website': 'https://www.cafeoma.com/'}}, {'type': 'node', 'id': 666688399, 'lat': 4.6178721, 'lon': -74.1281357, 'tags': {'amenity': 'cafe', 'name': 'Terranova'}}, {'type': 'node', 'id': 679776620, 'lat': 4.5718378, 'lon': -74.1023154, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 695229274, 'lat': 4.7549816, 'lon': -74.0465828, 'tags': {'addr:city': 'Bogota', 'addr:country': 'CO', 'addr:housenumber': '45-9', 'addr:street': 'Calle 174A', 'amenity': 'cafe', 'brand': 'Tostao'}}, {'type': 'node', 'id': 756685866, 'lat': 4.52194, 'lon': -74.1212078, 'tags': {'amenity': 'cafe', 'name': 'WilPan'}}, {'type': 'node', 'id': 775392658, 'lat': 4.6880551, 'lon': -74.0692988, 'tags': {'addr:street': 'Calle 98', 'amenity': 'cafe', 'name': 'Limbapan', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 822152787, 'lat': 4.6336939, 'lon': -74.102892, 'tags': {'amenity': 'cafe', 'name': 'On the Run'}}, {'type': 'node', 'id': 849023912, 'lat': 4.6678858, 'lon': -74.0538027, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes', 'website': 'https://www.cafeoma.com/', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 859121163, 'lat': 4.7230014, 'lon': -74.0679086, 'tags': {'amenity': 'cafe', 'name': 'Wilsón'}}, {'type': 'node', 'id': 859648400, 'lat': 4.6643983, 'lon': -74.0613895, 'tags': {'amenity': 'cafe', 'wheelchair': 'no'}}, {'type': 'node', 'id': 878234750, 'lat': 4.6571319, 'lon': -74.0560636, 'tags': {'amenity': 'cafe', 'brand': 'Juan Valdez Café', 'brand:wikidata': 'Q6301102', 'brand:wikipedia': 'en:Juan Valdez Café', 'cuisine': 'coffee_shop', 'name': 'Juan Valdez Café', 'name:es': 'Juan Valdez Café', 'shop': 'coffee', 'takeaway': 'yes', 'website': 'https://juanvaldez.com/'}}, {'type': 'node', 'id': 954696710, 'lat': 4.6032593, 'lon': -74.0662201, 'tags': {'amenity': 'cafe', 'name': 'Doña Blanca'}}, {'type': 'node', 'id': 1040448121, 'lat': 4.6937664, 'lon': -74.0663162, 'tags': {'amenity': 'cafe', 'name': 'Salzig'}}, {'type': 'node', 'id': 1062675225, 'lat': 4.6661654, 'lon': -74.1260495, 'tags': {'addr:street': 'Carrera 82', 'amenity': 'cafe', 'name': 'Pan de Oro', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 1106833491, 'lat': 4.6034563, 'lon': -74.0725164, 'tags': {'amenity': 'cafe', 'name': 'Oma'}}, {'type': 'node', 'id': 1117605036, 'lat': 4.6302368, 'lon': -74.0748324, 'tags': {'addr:city': 'Bogotá', 'addr:street': 'Carrera 24', 'amenity': 'cafe', 'name': 'Panadería Arlequin', 'source': 'Kaart Ground Survey 2017'}}, {'type': 'node', 'id': 1118998288, 'lat': 4.6008511, 'lon': -74.0682011, 'tags': {'addr:housenumber': '2-51', 'addr:street': 'Calle 17', 'amenity': 'cafe', 'internet_access': 'yes', 'name': 'La Redada Miscelánea Cultural', 'phone': '571-3422107', 'website': 'www.laredada.org'}}, {'type': 'node', 'id': 1123520521, 'lat': 4.7559209, 'lon': -74.0516087, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1123520542, 'lat': 4.7558567, 'lon': -74.0506538, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1193385201, 'lat': 4.6570346, 'lon': -74.0578146, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 1201598234, 'lat': 4.6309608, 'lon': -74.0667937, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'name': 'Café OMA', 'takeaway': 'yes', 'website': 'https://www.cafeoma.com/'}}, {'type': 'node', 'id': 1268313156, 'lat': 4.6090909, 'lon': -74.0688278, 'tags': {'addr:city': 'Bogotá', 'addr:street': 'Calle 24', 'amenity': 'cafe', 'cuisine': 'Café_de_orígen', 'internet_access': 'yes', 'name': 'Café Recoleta', 'smoking': 'no'}}, {'type': 'node', 'id': 1277994075, 'lat': 4.635117, 'lon': -74.0750056, 'tags': {'amenity': 'cafe', 'cuisine': 'international', 'name': 'San Cafe'}}, {'type': 'node', 'id': 1336170374, 'lat': 4.5683626, 'lon': -74.0970217, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1383986709, 'lat': 4.6272621, 'lon': -74.0625932, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1384008514, 'lat': 4.6280968, 'lon': -74.0632359, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1384008521, 'lat': 4.628759, 'lon': -74.062728, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1384008566, 'lat': 4.630719, 'lon': -74.063903, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1451628087, 'lat': 4.6358633, 'lon': -74.0824368, 'tags': {'amenity': 'cafe', 'brand': 'Tostao’', 'brand:wikidata': 'Q60632476', 'building': 'university', 'cuisine': 'coffee_shop', 'name': 'Tostao’', 'name:es': 'Tostao’'}}, {'type': 'node', 'id': 1459466513, 'lat': 4.6717245, 'lon': -74.0591688, 'tags': {'amenity': 'cafe', 'name': 'Las Cafetales'}}, {'type': 'node', 'id': 1459468413, 'lat': 4.600109, 'lon': -74.0706196, 'tags': {'amenity': 'cafe', 'name': 'Rock al Horno'}}, {'type': 'node', 'id': 1459468418, 'lat': 4.6005428, 'lon': -74.0700032, 'tags': {'amenity': 'cafe', 'name': 'Hibrido', 'name:es': 'Hibrido'}}, {'type': 'node', 'id': 1460556480, 'lat': 4.5989831, 'lon': -74.0705608, 'tags': {'amenity': 'cafe', 'name': 'Cafe del sol'}}, {'type': 'node', 'id': 1586401453, 'lat': 4.7482454, 'lon': -74.0968103, 'tags': {'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name': 'Cafe OMA'}}, {'type': 'node', 'id': 1595604250, 'lat': 4.5040339, 'lon': -74.1149679, 'tags': {'amenity': 'cafe', 'name': 'Panadería y Cafeteria'}}, {'type': 'node', 'id': 1595608094, 'lat': 4.5049805, 'lon': -74.115051, 'tags': {'amenity': 'cafe', 'name': 'Panadería'}}, {'type': 'node', 'id': 1615705927, 'lat': 4.6467244, 'lon': -74.0601618, 'tags': {'addr:city': 'Bogotá', 'addr:full': 'Cra 7 # 61-52', 'amenity': 'cafe', 'brand': 'Tostao’', 'brand:wikidata': 'Q60632476', 'cuisine': 'coffee_shop', 'internet_access': 'wlan', 'internet_access:fee': 'no', 'name': 'Tostao’', 'name:es': 'Tostao’', 'operator': 'Café Juan Valdez', 'shop': 'beverages', 'smoking': 'yes', 'wheelchair': 'no'}}, {'type': 'node', 'id': 1615705933, 'lat': 4.6453457, 'lon': -74.0575346, 'tags': {'addr:city': 'Bogotá D.C.', 'addr:housenumber': '61-42', 'addr:street': 'Carrera 3B', 'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 1624309379, 'lat': 4.6325899, 'lon': -74.0746713, 'tags': {'addr:housename': 'Calle 42', 'addr:housenumber': '22-54', 'amenity': 'cafe', 'cuisine': 'spanish', 'name': 'El Cafetín de la Soledad', 'wifi': 'free'}}, {'type': 'node', 'id': 1634612585, 'lat': 4.7413943, 'lon': -74.0345859, 'tags': {'amenity': 'cafe', 'brand': 'Tostao’', 'brand:wikidata': 'Q60632476', 'cuisine': 'coffee_shop', 'name': 'Tostao’', 'name:es': 'Tostao’', 'official_name': 'TOSTAO’ Café & Pan', 'takeaway': 'yes'}}, {'type': 'node', 'id': 1659534257, 'lat': 4.69782, 'lon': -74.0477571, 'tags': {'amenity': 'cafe', 'name': 'Juan Valdez Cafe', 'website': 'https://juanvaldez.com/', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 1659534258, 'lat': 4.6978435, 'lon': -74.0478151, 'tags': {'amenity': 'cafe', 'cuisine': 'pasteleria', 'name': 'amínta', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 1660844410, 'lat': 4.6974846, 'lon': -74.0329179, 'tags': {'amenity': 'cafe', 'name': 'Doña DIcha', 'wheelchair': 'no'}}, {'type': 'node', 'id': 1661478291, 'lat': 4.6784727, 'lon': -74.0465928, 'tags': {'amenity': 'cafe', 'cuisine': 'coffee_shop', 'internet_access': 'wlan', 'name': 'El Deseo'}}, {'type': 'node', 'id': 1661487943, 'lat': 4.6801863, 'lon': -74.0482048, 'tags': {'amenity': 'cafe', 'name': 'Diletto', 'wheelchair': 'limited'}}, {'type': 'node', 'id': 1824986067, 'lat': 4.6660569, 'lon': -74.0556673, 'tags': {'amenity': 'cafe', 'brand': 'Juan Valdez Café', 'brand:wikidata': 'Q6301102', 'brand:wikipedia': 'en:Juan Valdez Café', 'cuisine': 'coffee_shop', 'name': 'Juan Valdez Café', 'name:es': 'Juan Valdez Café', 'shop': 'coffee', 'takeaway': 'yes', 'website': 'https://juanvaldez.com/', 'wheelchair': 'yes'}}, {'type': 'node', 'id': 1855061085, 'lat': 4.6636139, 'lon': -74.0579561, 'tags': {'addr:street': 'Calle 77', 'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'name': 'Café OMA', 'source': 'Kaart Ground Survey 2017', 'takeaway': 'yes', 'website': 'https://www.cafeoma.com/'}}, {'type': 'node', 'id': 1882851241, 'lat': 4.6276756, 'lon': -74.063023, 'tags': {'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'name': 'Café OMA', 'takeaway': 'yes', 'website': 'https://www.cafeoma.com/'}}, {'type': 'node', 'id': 1882851262, 'lat': 4.6265561, 'lon': -74.065059, 'tags': {'amenity': 'cafe', 'description': 'CafeteriaPiso2'}}, {'type': 'node', 'id': 1882851269, 'lat': 4.6268031, 'lon': -74.0636183, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1882851275, 'lat': 4.62695, 'lon': -74.0650021, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1882851292, 'lat': 4.628034, 'lon': -74.0643982, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1882851302, 'lat': 4.6286548, 'lon': -74.0640631, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1934487139, 'lat': 4.6337398, 'lon': -74.0855876, 'tags': {'amenity': 'cafe', 'building': 'university', 'name': 'Cafeteria Geologia'}}, {'type': 'node', 'id': 1940810948, 'lat': 4.6448735, 'lon': -74.1657269, 'tags': {'amenity': 'cafe', 'name': 'Panadería Natys'}}, {'type': 'node', 'id': 1986116926, 'lat': 4.718695, 'lon': -74.035439, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 1986209954, 'lat': 4.7201407, 'lon': -74.0380722, 'tags': {'addr:street': 'Calle 140', 'amenity': 'cafe', 'brand': 'Juan Valdez Café', 'brand:wikidata': 'Q6301102', 'brand:wikipedia': 'en:Juan Valdez Café', 'cuisine': 'coffee_shop', 'name': 'Juan Valdez Café', 'name:es': 'Juan Valdez Café', 'shop': 'coffee', 'source': 'Kaart Ground Survey 2017', 'takeaway': 'yes', 'website': 'https://juanvaldez.com/'}}, {'type': 'node', 'id': 2021967796, 'lat': 4.6007912, 'lon': -74.0651978, 'tags': {'addr:housename': 'Bloque N, primer piso', 'addr:place': 'Universidad de los Andes', 'amenity': 'cafe', 'diet:vegetarian': 'yes', 'internet_access': 'wlan', 'internet_access:fee': 'no', 'name': 'Cafeteria Central', 'opening_hours': 'Mo-Fr 07:00-20:00', 'opening_hours:es': 'Lu-Vi 7:00-20:00', 'operator': 'Dialimentos', 'smoking': 'no', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-dialimentos', 'wheelchair': 'yes', 'wifi': 'yes'}}, {'type': 'node', 'id': 2021979046, 'lat': 4.6007113, 'lon': -74.0660095, 'tags': {'addr:housename': 'Bloque z, galpón', 'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 2023673410, 'lat': 4.601636, 'lon': -74.0645381, 'tags': {'addr:housename': 'Bloque V', 'amenity': 'cafe', 'internet_access': 'wlan', 'name': 'Café Kaldivia', 'url': 'https://campusinfo.uniandes.edu.co/es/recursos/edificios/elcampito', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Alimentos-Spress', 'wheelchair': 'no', 'wifi': 'yes'}}, {'type': 'node', 'id': 2023682954, 'lat': 4.6018583, 'lon': -74.0653355, 'tags': {'addr:housename': 'Plazoleta Lleras', 'amenity': 'cafe', 'name': 'Las Monas', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Alimentos-Spress'}}, {'type': 'node', 'id': 2023685769, 'lat': 4.6003182, 'lon': -74.0650277, 'tags': {'addr:housename': 'Bloque Q terraza', 'amenity': 'cafe', 'name': 'La Frutería', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-L-Fruiterie'}}, {'type': 'node', 'id': 2023692417, 'lat': 4.6024274, 'lon': -74.0655533, 'tags': {'addr:housename': 'Bloque z, galpón', 'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 2023697512, 'lat': 4.6016681, 'lon': -74.0642122, 'tags': {'addr:housename': 'Plazoleta Richard', 'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 2023701871, 'lat': 4.6027797, 'lon': -74.0645256, 'tags': {'addr:housename': 'Biblioteca General, 3er piso', 'amenity': 'cafe', 'brand': 'Café OMA', 'brand:wikidata': 'Q108929487', 'cuisine': 'coffee_shop', 'level': '3', 'name': 'Café OMA', 'takeaway': 'yes'}}, {'type': 'node', 'id': 2023718129, 'lat': 4.6028332, 'lon': -74.0647332, 'tags': {'addr:housename': 'Edificio Mario Laserna, punto central, quinto piso', 'amenity': 'cafe', 'level': '5', 'name': 'Cascabel', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Cascabel'}}, {'type': 'node', 'id': 2023726080, 'lat': 4.6026038, 'lon': -74.0663929, 'tags': {'addr:housename': 'Bloque AU, primer piso', 'amenity': 'cafe', 'name': 'Cascabel', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Cascabel'}}, {'type': 'node', 'id': 2023735292, 'lat': 4.6027455, 'lon': -74.0645958, 'tags': {'addr:housename': 'Edificio Mario Laserna, puntos laterales, 5to piso', 'amenity': 'cafe', 'level': '5', 'name': 'GRATTO', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Gratto'}}, {'type': 'node', 'id': 2023742114, 'lat': 4.6000212, 'lon': -74.0628309, 'tags': {'addr:housename': 'Centro Deportivo, segundo piso', 'amenity': 'cafe', 'name': 'Oma', 'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Goddard-Centro-deportivo'}}, {'type': 'node', 'id': 2078082049, 'lat': 4.5986425, 'lon': -74.0703923, 'tags': {'addr:housenumber': '3-19', 'addr:street': 'Calle 12C', 'amenity': 'cafe', 'name': 'Explora Hostel', 'tourism': 'hostel'}}, {'type': 'node', 'id': 2078082050, 'lat': 4.5970383, 'lon': -74.0696065, 'tags': {'addr:housenumber': '13-12', 'addr:street': 'Carrera 1A', 'amenity': 'cafe', 'cuisine': 'regional', 'internet_access': 'wlan', 'name': 'El gato gris', 'name:es': 'El gato gris', 'opening_hours': 'Mo-Th 08:00-01:00; Fr-Sa 08:00-02:00; Su 12:00-00:00', 'website': 'https://www.gatogris.com/'}}, {'type': 'node', 'id': 2178467978, 'lat': 4.6437983, 'lon': -74.0649454, 'tags': {'amenity': 'cafe'}}, {'type': 'node', 'id': 2178595768, 'lat': 4.6299118, 'lon': -74.0640645, 'tags': {'amenity': 'cafe', 'name': 'Cafetería El Cotidiano'}}, {'type': 'node', 'id': 2178595769, 'lat': 4.629289, 'lon': -74.064331, 'tags': {'amenity': 'cafe', 'name': 'Subway Basicas'}}, {'type': 'node', 'id': 2295113172, 'lat': 4.6130271, 'lon': -74.0666541, 'tags': {'addr:city': 'Bogota', 'addr:housenumber': '26C-13', 'addr:street': 'Carrera 4A', 'amenity': 'cafe', 'cuisine': 'Chocolate_shop', 'internet_access': 'yes', 'name': 'Lacho

In [ ]:
#Imprimimos en pantalla el JSON data_cafes de forma que se vea más legible
import json
print(json.dumps(data_cafes, indent=2))

{
  "version": 0.6,
  "generator": "Overpass API 0.7.62.4 2390de5a",
  "osm3s": {
    "timestamp_osm_base": "2025-02-12T00:30:20Z",
    "timestamp_areas_base": "2024-12-31T00:49:33Z",
    "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL."
  },
  "elements": [
    {
      "type": "node",
      "id": 265501503,
      "lat": 4.6396774,
      "lon": -74.0630225,
      "tags": {
        "amenity": "cafe",
        "brand": "Juan Valdez Caf\u00e9",
        "brand:wikidata": "Q6301102",
        "brand:wikipedia": "en:Juan Valdez Caf\u00e9",
        "cuisine": "coffee_shop",
        "name": "Juan Valdez Caf\u00e9",
        "name:es": "Juan Valdez Caf\u00e9",
        "shop": "coffee",
        "takeaway": "yes",
        "website": "https://juanvaldez.com/"
      }
    },
    {
      "type": "node",
      "id": 265501535,
      "lat": 4.6402868,
      "lon": -74.0628995,
      "tags": {
        "addr:street": "Avenida Carrera 7",
        "amenity": "cafe",
        "name": "La Cafeteria",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 340429454,
      "lat": 4.6761001,
      "lon": -74.0475614,
      "tags": {
        "amenity": "cafe",
        "brand": "Juan Valdez Caf\u00e9",
        "brand:wikidata": "Q6301102",
        "brand:wikipedia": "en:Juan Valdez Caf\u00e9",
        "cuisine": "coffee_shop",
        "name": "Juan Valdez Caf\u00e9",
        "name:es": "Juan Valdez Caf\u00e9",
        "opening_hours": "Mo-Su 07:00-22:00",
        "shop": "coffee",
        "takeaway": "yes",
        "website": "https://juanvaldez.com/",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 368176844,
      "lat": 4.6504734,
      "lon": -74.0917405,
      "tags": {
        "amenity": "cafe",
        "name": "Salon de T\u00e9 F&W"
      }
    },
    {
      "type": "node",
      "id": 405236743,
      "lat": 4.7070904,
      "lon": -74.0581185,
      "tags": {
        "amenity": "cafe",
        "brand": "Pan Pa' Ya!",
        "brand:wikidata": "Q131744932",
        "level": "0",
        "name": "Pan Pa' Ya!",
        "payment:cards": "yes",
        "payment:cash": "yes",
        "service:electricity": "no",
        "shop": "bakery",
        "smoking": "no",
        "wheelchair": "yes"
      }
    },
    {
      "type": "node",
      "id": 460405530,
      "lat": 4.6580768,
      "lon": -74.1118237,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 485363102,
      "lat": 4.6824213,
      "lon": -74.0488925,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes",
        "website": "https://www.cafeoma.com/",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 485536579,
      "lat": 4.7267619,
      "lon": -74.0357369,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 494767144,
      "lat": 4.7614606,
      "lon": -74.0437824,
      "tags": {
        "amenity": "cafe",
        "name": "El marinero"
      }
    },
    {
      "type": "node",
      "id": 499109158,
      "lat": 4.7717566,
      "lon": -74.0423748,
      "tags": {
        "amenity": "cafe",
        "name": "On the run"
      }
    },
    {
      "type": "node",
      "id": 501789966,
      "lat": 4.6668322,
      "lon": -74.0525611,
      "tags": {
        "amenity": "cafe",
        "brand": "Juan Valdez Caf\u00e9",
        "brand:wikidata": "Q6301102",
        "brand:wikipedia": "en:Juan Valdez Caf\u00e9",
        "cuisine": "coffee_shop",
        "name": "Juan Valdez Caf\u00e9",
        "name:es": "Juan Valdez Caf\u00e9",
        "shop": "coffee",
        "takeaway": "yes",
        "website": "https://juanvaldez.com/",
        "wheelchair": "no"
      }
    },
    {
      "type": "node",
      "id": 505075470,
      "lat": 4.6979174,
      "lon": -74.0691586,
      "tags": {
        "addr:street": "Avenida Suba",
        "amenity": "cafe",
        "name": "Autopan",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 506310009,
      "lat": 4.7387233,
      "lon": -74.0443946,
      "tags": {
        "amenity": "cafe",
        "name": "Cafe internet"
      }
    },
    {
      "type": "node",
      "id": 506542813,
      "lat": 4.7290096,
      "lon": -74.0408665,
      "tags": {
        "addr:street": "Avenida Cedritos",
        "amenity": "cafe",
        "brand": "Pan Pa' Ya!",
        "brand:wikidata": "Q131744932",
        "name": "Pan Pa' Ya!",
        "shop": "bakery",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 517123861,
      "lat": 4.6910866,
      "lon": -74.1003074,
      "tags": {
        "amenity": "cafe",
        "name": "Festytortas"
      }
    },
    {
      "type": "node",
      "id": 529748669,
      "lat": 4.6430295,
      "lon": -74.101606,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 595598570,
      "lat": 4.6703265,
      "lon": -74.1062994,
      "tags": {
        "amenity": "cafe",
        "name": "Pasteleria Santander"
      }
    },
    {
      "type": "node",
      "id": 600238725,
      "lat": 4.701068,
      "lon": -74.115428,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "cuisine": "coffee_shop",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes"
      }
    },
    {
      "type": "node",
      "id": 601254785,
      "lat": 4.6425553,
      "lon": -74.1348505,
      "tags": {
        "addr:city": "Kennedy",
        "addr:street": "Carrera 72A",
        "amenity": "cafe",
        "name": "Meridianos Pan y Cafe",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 601255096,
      "lat": 4.6577458,
      "lon": -74.1182451,
      "tags": {
        "amenity": "cafe",
        "name": "Pan Suizo"
      }
    },
    {
      "type": "node",
      "id": 605667595,
      "lat": 4.6503058,
      "lon": -74.0870628,
      "tags": {
        "amenity": "cafe",
        "name": "Picos y Cafe"
      }
    },
    {
      "type": "node",
      "id": 614660111,
      "lat": 4.7281189,
      "lon": -74.0648271,
      "tags": {
        "amenity": "cafe",
        "name": "Juan Vald\u00e9s"
      }
    },
    {
      "type": "node",
      "id": 616522538,
      "lat": 4.7109718,
      "lon": -74.140064,
      "tags": {
        "addr:street": "Calle 64",
        "amenity": "cafe",
        "name": "Monserrate",
        "shop": "bakery",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 662221657,
      "lat": 4.6836004,
      "lon": -74.0804715,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes",
        "website": "https://www.cafeoma.com/"
      }
    },
    {
      "type": "node",
      "id": 666688399,
      "lat": 4.6178721,
      "lon": -74.1281357,
      "tags": {
        "amenity": "cafe",
        "name": "Terranova"
      }
    },
    {
      "type": "node",
      "id": 679776620,
      "lat": 4.5718378,
      "lon": -74.1023154,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 695229274,
      "lat": 4.7549816,
      "lon": -74.0465828,
      "tags": {
        "addr:city": "Bogota",
        "addr:country": "CO",
        "addr:housenumber": "45-9",
        "addr:street": "Calle 174A",
        "amenity": "cafe",
        "brand": "Tostao"
      }
    },
    {
      "type": "node",
      "id": 756685866,
      "lat": 4.52194,
      "lon": -74.1212078,
      "tags": {
        "amenity": "cafe",
        "name": "WilPan"
      }
    },
    {
      "type": "node",
      "id": 775392658,
      "lat": 4.6880551,
      "lon": -74.0692988,
      "tags": {
        "addr:street": "Calle 98",
        "amenity": "cafe",
        "name": "Limbapan",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 822152787,
      "lat": 4.6336939,
      "lon": -74.102892,
      "tags": {
        "amenity": "cafe",
        "name": "On the Run"
      }
    },
    {
      "type": "node",
      "id": 849023912,
      "lat": 4.6678858,
      "lon": -74.0538027,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "cuisine": "coffee_shop",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes",
        "website": "https://www.cafeoma.com/",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 859121163,
      "lat": 4.7230014,
      "lon": -74.0679086,
      "tags": {
        "amenity": "cafe",
        "name": "Wils\u00f3n"
      }
    },
    {
      "type": "node",
      "id": 859648400,
      "lat": 4.6643983,
      "lon": -74.0613895,
      "tags": {
        "amenity": "cafe",
        "wheelchair": "no"
      }
    },
    {
      "type": "node",
      "id": 878234750,
      "lat": 4.6571319,
      "lon": -74.0560636,
      "tags": {
        "amenity": "cafe",
        "brand": "Juan Valdez Caf\u00e9",
        "brand:wikidata": "Q6301102",
        "brand:wikipedia": "en:Juan Valdez Caf\u00e9",
        "cuisine": "coffee_shop",
        "name": "Juan Valdez Caf\u00e9",
        "name:es": "Juan Valdez Caf\u00e9",
        "shop": "coffee",
        "takeaway": "yes",
        "website": "https://juanvaldez.com/"
      }
    },
    {
      "type": "node",
      "id": 954696710,
      "lat": 4.6032593,
      "lon": -74.0662201,
      "tags": {
        "amenity": "cafe",
        "name": "Do\u00f1a Blanca"
      }
    },
    {
      "type": "node",
      "id": 1040448121,
      "lat": 4.6937664,
      "lon": -74.0663162,
      "tags": {
        "amenity": "cafe",
        "name": "Salzig"
      }
    },
    {
      "type": "node",
      "id": 1062675225,
      "lat": 4.6661654,
      "lon": -74.1260495,
      "tags": {
        "addr:street": "Carrera 82",
        "amenity": "cafe",
        "name": "Pan de Oro",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 1106833491,
      "lat": 4.6034563,
      "lon": -74.0725164,
      "tags": {
        "amenity": "cafe",
        "name": "Oma"
      }
    },
    {
      "type": "node",
      "id": 1117605036,
      "lat": 4.6302368,
      "lon": -74.0748324,
      "tags": {
        "addr:city": "Bogot\u00e1",
        "addr:street": "Carrera 24",
        "amenity": "cafe",
        "name": "Panader\u00eda Arlequin",
        "source": "Kaart Ground Survey 2017"
      }
    },
    {
      "type": "node",
      "id": 1118998288,
      "lat": 4.6008511,
      "lon": -74.0682011,
      "tags": {
        "addr:housenumber": "2-51",
        "addr:street": "Calle 17",
        "amenity": "cafe",
        "internet_access": "yes",
        "name": "La Redada Miscel\u00e1nea Cultural",
        "phone": "571-3422107",
        "website": "www.laredada.org"
      }
    },
    {
      "type": "node",
      "id": 1123520521,
      "lat": 4.7559209,
      "lon": -74.0516087,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1123520542,
      "lat": 4.7558567,
      "lon": -74.0506538,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1193385201,
      "lat": 4.6570346,
      "lon": -74.0578146,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "cuisine": "coffee_shop",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes"
      }
    },
    {
      "type": "node",
      "id": 1201598234,
      "lat": 4.6309608,
      "lon": -74.0667937,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes",
        "website": "https://www.cafeoma.com/"
      }
    },
    {
      "type": "node",
      "id": 1268313156,
      "lat": 4.6090909,
      "lon": -74.0688278,
      "tags": {
        "addr:city": "Bogot\u00e1",
        "addr:street": "Calle 24",
        "amenity": "cafe",
        "cuisine": "Caf\u00e9_de_or\u00edgen",
        "internet_access": "yes",
        "name": "Caf\u00e9 Recoleta",
        "smoking": "no"
      }
    },
    {
      "type": "node",
      "id": 1277994075,
      "lat": 4.635117,
      "lon": -74.0750056,
      "tags": {
        "amenity": "cafe",
        "cuisine": "international",
        "name": "San Cafe"
      }
    },
    {
      "type": "node",
      "id": 1336170374,
      "lat": 4.5683626,
      "lon": -74.0970217,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1383986709,
      "lat": 4.6272621,
      "lon": -74.0625932,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1384008514,
      "lat": 4.6280968,
      "lon": -74.0632359,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1384008521,
      "lat": 4.628759,
      "lon": -74.062728,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1384008566,
      "lat": 4.630719,
      "lon": -74.063903,
      "tags": {
        "amenity": "cafe"
      }
    },
    {
      "type": "node",
      "id": 1451628087,
      "lat": 4.6358633,
      "lon": -74.0824368,
      "tags": {
        "amenity": "cafe",
        "brand": "Tostao\u2019",
        "brand:wikidata": "Q60632476",
        "building": "university",
        "cuisine": "coffee_shop",
        "name": "Tostao\u2019",
        "name:es": "Tostao\u2019"
      }
    },
    {
      "type": "node",
      "id": 1459466513,
      "lat": 4.6717245,
      "lon": -74.0591688,
      "tags": {
        "amenity": "cafe",
        "name": "Las Cafetales"
      }
    },
    {
      "type": "node",
      "id": 1459468413,
      "lat": 4.600109,
      "lon": -74.0706196,
      "tags": {
        "amenity": "cafe",
        "name": "Rock al Horno"
      }
    },
    {
      "type": "node",
      "id": 1459468418,
      "lat": 4.6005428,
      "lon": -74.0700032,
      "tags": {
        "amenity": "cafe",
        "name": "Hibrido",
        "name:es": "Hibrido"
      }
    },
    {
      "type": "node",
      "id": 1460556480,
      "lat": 4.5989831,
      "lon": -74.0705608,
      "tags": {
        "amenity": "cafe",
        "name": "Cafe del sol"
      }
    },
    {
      "type": "node",
      "id": 1586401453,
      "lat": 4.7482454,
      "lon": -74.0968103,
      "tags": {
        "amenity": "cafe",
        "cuisine": "coffee_shop",
        "name": "Cafe OMA"
      }
    },
    {
      "type": "node",
      "id": 1595604250,
      "lat": 4.5040339,
      "lon": -74.1149679,
      "tags": {
        "amenity": "cafe",
        "name": "Panader\u00eda y Cafeteria"
      }
    },
    {
      "type": "node",
      "id": 1595608094,
      "lat": 4.5049805,
      "lon": -74.115051,
      "tags": {
        "amenity": "cafe",
        "name": "Panader\u00eda"
      }
    },
    {
      "type": "node",
      "id": 1615705927,
      "lat": 4.6467244,
      "lon": -74.0601618,
      "tags": {
        "addr:city": "Bogot\u00e1",
        "addr:full": "Cra 7 # 61-52",
        "amenity": "cafe",
        "brand": "Tostao\u2019",
        "brand:wikidata": "Q60632476",
        "cuisine": "coffee_shop",
        "internet_access": "wlan",
        "internet_access:fee": "no",
        "name": "Tostao\u2019",
        "name:es": "Tostao\u2019",
        "operator": "Caf\u00e9 Juan Valdez",
        "shop": "beverages",
        "smoking": "yes",
        "wheelchair": "no"
      }
    },
    {
      "type": "node",
      "id": 1615705933,
      "lat": 4.6453457,
      "lon": -74.0575346,
      "tags": {
        "addr:city": "Bogot\u00e1 D.C.",
        "addr:housenumber": "61-42",
        "addr:street": "Carrera 3B",
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "cuisine": "coffee_shop",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes"
      }
    },
    {
      "type": "node",
      "id": 1624309379,
      "lat": 4.6325899,
      "lon": -74.0746713,
      "tags": {
        "addr:housename": "Calle 42",
        "addr:housenumber": "22-54",
        "amenity": "cafe",
        "cuisine": "spanish",
        "name": "El Cafet\u00edn de la Soledad",
        "wifi": "free"
      }
    },
    {
      "type": "node",
      "id": 1634612585,
      "lat": 4.7413943,
      "lon": -74.0345859,
      "tags": {
        "amenity": "cafe",
        "brand": "Tostao\u2019",
        "brand:wikidata": "Q60632476",
        "cuisine": "coffee_shop",
        "name": "Tostao\u2019",
        "name:es": "Tostao\u2019",
        "official_name": "TOSTAO\u2019 Caf\u00e9 & Pan",
        "takeaway": "yes"
      }
    },
    {
      "type": "node",
      "id": 1659534257,
      "lat": 4.69782,
      "lon": -74.0477571,
      "tags": {
        "amenity": "cafe",
        "name": "Juan Valdez Cafe",
        "website": "https://juanvaldez.com/",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 1659534258,
      "lat": 4.6978435,
      "lon": -74.0478151,
      "tags": {
        "amenity": "cafe",
        "cuisine": "pasteleria",
        "name": "am\u00ednta",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 1660844410,
      "lat": 4.6974846,
      "lon": -74.0329179,
      "tags": {
        "amenity": "cafe",
        "name": "Do\u00f1a DIcha",
        "wheelchair": "no"
      }
    },
    {
      "type": "node",
      "id": 1661478291,
      "lat": 4.6784727,
      "lon": -74.0465928,
      "tags": {
        "amenity": "cafe",
        "cuisine": "coffee_shop",
        "internet_access": "wlan",
        "name": "El Deseo"
      }
    },
    {
      "type": "node",
      "id": 1661487943,
      "lat": 4.6801863,
      "lon": -74.0482048,
      "tags": {
        "amenity": "cafe",
        "name": "Diletto",
        "wheelchair": "limited"
      }
    },
    {
      "type": "node",
      "id": 1824986067,
      "lat": 4.6660569,
      "lon": -74.0556673,
      "tags": {
        "amenity": "cafe",
        "brand": "Juan Valdez Caf\u00e9",
        "brand:wikidata": "Q6301102",
        "brand:wikipedia": "en:Juan Valdez Caf\u00e9",
        "cuisine": "coffee_shop",
        "name": "Juan Valdez Caf\u00e9",
        "name:es": "Juan Valdez Caf\u00e9",
        "shop": "coffee",
        "takeaway": "yes",
        "website": "https://juanvaldez.com/",
        "wheelchair": "yes"
      }
    },
    {
      "type": "node",
      "id": 1855061085,
      "lat": 4.6636139,
      "lon": -74.0579561,
      "tags": {
        "addr:street": "Calle 77",
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "name": "Caf\u00e9 OMA",
        "source": "Kaart Ground Survey 2017",
        "takeaway": "yes",
        "website": "https://www.cafeoma.com/"
      }
    },
    {
      "type": "node",
      "id": 1882851241,
      "lat": 4.6276756,
      "lon": -74.063023,
      "tags": {
        "amenity": "cafe",
        "brand": "Caf\u00e9 OMA",
        "brand:wikidata": "Q108929487",
        "name": "Caf\u00e9 OMA",
        "takeaway": "yes",
        "website": "https://www.cafeoma.com/"
      }
    },
    {
      "type": "node",
      "id": 1882851262,
      "lat": 4.6265561,
      "lon": -74.065059,
      "tags": {
        "amenity": "cafe",
        "description": "CafeteriaPiso2"
      }

In [ ]:
data_cafes["elements"]

[{'type': 'node',
  'id': 265501503,
  'lat': 4.6396774,
  'lon': -74.0630225,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/'}},
 {'type': 'node',
  'id': 265501535,
  'lat': 4.6402868,
  'lon': -74.0628995,
  'tags': {'addr:street': 'Avenida Carrera 7',
   'amenity': 'cafe',
   'name': 'La Cafeteria',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 340429454,
  'lat': 4.6761001,
  'lon': -74.0475614,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'opening_hours': 'Mo-Su 07:00-22:00',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 368176844,
  'lat': 4.6504734,
  'lon': -74.0917405,
  'tags': {'amenity': 'cafe', 'name': 'Salon de Té F&W'}},
 {'type': 'node',
  'id': 405236743,
  'lat': 4.7070904,
  'lon': -74.0581185,
  'tags': {'amenity': 'cafe',
   'brand': "Pan Pa' Ya!",
   'brand:wikidata': 'Q131744932',
   'level': '0',
   'name': "Pan Pa' Ya!",
   'payment:cards': 'yes',
   'payment:cash': 'yes',
   'service:electricity': 'no',
   'shop': 'bakery',
   'smoking': 'no',
   'wheelchair': 'yes'}},
 {'type': 'node',
  'id': 460405530,
  'lat': 4.6580768,
  'lon': -74.1118237,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 485363102,
  'lat': 4.6824213,
  'lon': -74.0488925,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 485536579,
  'lat': 4.7267619,
  'lon': -74.0357369,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 494767144,
  'lat': 4.7614606,
  'lon': -74.0437824,
  'tags': {'amenity': 'cafe', 'name': 'El marinero'}},
 {'type': 'node',
  'id': 499109158,
  'lat': 4.7717566,
  'lon': -74.0423748,
  'tags': {'amenity': 'cafe', 'name': 'On the run'}},
 {'type': 'node',
  'id': 501789966,
  'lat': 4.6668322,
  'lon': -74.0525611,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'no'}},
 {'type': 'node',
  'id': 505075470,
  'lat': 4.6979174,
  'lon': -74.0691586,
  'tags': {'addr:street': 'Avenida Suba',
   'amenity': 'cafe',
   'name': 'Autopan',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 506310009,
  'lat': 4.7387233,
  'lon': -74.0443946,
  'tags': {'amenity': 'cafe', 'name': 'Cafe internet'}},
 {'type': 'node',
  'id': 506542813,
  'lat': 4.7290096,
  'lon': -74.0408665,
  'tags': {'addr:street': 'Avenida Cedritos',
   'amenity': 'cafe',
   'brand': "Pan Pa' Ya!",
   'brand:wikidata': 'Q131744932',
   'name': "Pan Pa' Ya!",
   'shop': 'bakery',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 517123861,
  'lat': 4.6910866,
  'lon': -74.1003074,
  'tags': {'amenity': 'cafe', 'name': 'Festytortas'}},
 {'type': 'node',
  'id': 529748669,
  'lat': 4.6430295,
  'lon': -74.101606,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 595598570,
  'lat': 4.6703265,
  'lon': -74.1062994,
  'tags': {'amenity': 'cafe', 'name': 'Pasteleria Santander'}},
 {'type': 'node',
  'id': 600238725,
  'lat': 4.701068,
  'lon': -74.115428,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 601254785,
  'lat': 4.6425553,
  'lon': -74.1348505,
  'tags': {'addr:city': 'Kennedy',
   'addr:street': 'Carrera 72A',
   'amenity': 'cafe',
   'name': 'Meridianos Pan y Cafe',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 601255096,
  'lat': 4.6577458,
  'lon': -74.1182451,
  'tags': {'amenity': 'cafe', 'name': 'Pan Suizo'}},
 {'type': 'node',
  'id': 605667595,
  'lat': 4.6503058,
  'lon': -74.0870628,
  'tags': {'amenity': 'cafe', 'name': 'Picos y Cafe'}},
 {'type': 'node',
  'id': 614660111,
  'lat': 4.7281189,
  'lon': -74.0648271,
  'tags': {'amenity': 'cafe', 'name': 'Juan Valdés'}},
 {'type': 'node',
  'id': 616522538,
  'lat': 4.7109718,
  'lon': -74.140064,
  'tags': {'addr:street': 'Calle 64',
   'amenity': 'cafe',
   'name': 'Monserrate',
   'shop': 'bakery',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 662221657,
  'lat': 4.6836004,
  'lon': -74.0804715,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 666688399,
  'lat': 4.6178721,
  'lon': -74.1281357,
  'tags': {'amenity': 'cafe', 'name': 'Terranova'}},
 {'type': 'node',
  'id': 679776620,
  'lat': 4.5718378,
  'lon': -74.1023154,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 695229274,
  'lat': 4.7549816,
  'lon': -74.0465828,
  'tags': {'addr:city': 'Bogota',
   'addr:country': 'CO',
   'addr:housenumber': '45-9',
   'addr:street': 'Calle 174A',
   'amenity': 'cafe',
   'brand': 'Tostao'}},
 {'type': 'node',
  'id': 756685866,
  'lat': 4.52194,
  'lon': -74.1212078,
  'tags': {'amenity': 'cafe', 'name': 'WilPan'}},
 {'type': 'node',
  'id': 775392658,
  'lat': 4.6880551,
  'lon': -74.0692988,
  'tags': {'addr:street': 'Calle 98',
   'amenity': 'cafe',
   'name': 'Limbapan',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 822152787,
  'lat': 4.6336939,
  'lon': -74.102892,
  'tags': {'amenity': 'cafe', 'name': 'On the Run'}},
 {'type': 'node',
  'id': 849023912,
  'lat': 4.6678858,
  'lon': -74.0538027,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 859121163,
  'lat': 4.7230014,
  'lon': -74.0679086,
  'tags': {'amenity': 'cafe', 'name': 'Wilsón'}},
 {'type': 'node',
  'id': 859648400,
  'lat': 4.6643983,
  'lon': -74.0613895,
  'tags': {'amenity': 'cafe', 'wheelchair': 'no'}},
 {'type': 'node',
  'id': 878234750,
  'lat': 4.6571319,
  'lon': -74.0560636,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/'}},
 {'type': 'node',
  'id': 954696710,
  'lat': 4.6032593,
  'lon': -74.0662201,
  'tags': {'amenity': 'cafe', 'name': 'Doña Blanca'}},
 {'type': 'node',
  'id': 1040448121,
  'lat': 4.6937664,
  'lon': -74.0663162,
  'tags': {'amenity': 'cafe', 'name': 'Salzig'}},
 {'type': 'node',
  'id': 1062675225,
  'lat': 4.6661654,
  'lon': -74.1260495,
  'tags': {'addr:street': 'Carrera 82',
   'amenity': 'cafe',
   'name': 'Pan de Oro',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 1106833491,
  'lat': 4.6034563,
  'lon': -74.0725164,
  'tags': {'amenity': 'cafe', 'name': 'Oma'}},
 {'type': 'node',
  'id': 1117605036,
  'lat': 4.6302368,
  'lon': -74.0748324,
  'tags': {'addr:city': 'Bogotá',
   'addr:street': 'Carrera 24',
   'amenity': 'cafe',
   'name': 'Panadería Arlequin',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 1118998288,
  'lat': 4.6008511,
  'lon': -74.0682011,
  'tags': {'addr:housenumber': '2-51',
   'addr:street': 'Calle 17',
   'amenity': 'cafe',
   'internet_access': 'yes',
   'name': 'La Redada Miscelánea Cultural',
   'phone': '571-3422107',
   'website': 'www.laredada.org'}},
 {'type': 'node',
  'id': 1123520521,
  'lat': 4.7559209,
  'lon': -74.0516087,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1123520542,
  'lat': 4.7558567,
  'lon': -74.0506538,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1193385201,
  'lat': 4.6570346,
  'lon': -74.0578146,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 1201598234,
  'lat': 4.6309608,
  'lon': -74.0667937,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 1268313156,
  'lat': 4.6090909,
  'lon': -74.0688278,
  'tags': {'addr:city': 'Bogotá',
   'addr:street': 'Calle 24',
   'amenity': 'cafe',
   'cuisine': 'Café_de_orígen',
   'internet_access': 'yes',
   'name': 'Café Recoleta',
   'smoking': 'no'}},
 {'type': 'node',
  'id': 1277994075,
  'lat': 4.635117,
  'lon': -74.0750056,
  'tags': {'amenity': 'cafe', 'cuisine': 'international', 'name': 'San Cafe'}},
 {'type': 'node',
  'id': 1336170374,
  'lat': 4.5683626,
  'lon': -74.0970217,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1383986709,
  'lat': 4.6272621,
  'lon': -74.0625932,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1384008514,
  'lat': 4.6280968,
  'lon': -74.0632359,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1384008521,
  'lat': 4.628759,
  'lon': -74.062728,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1384008566,
  'lat': 4.630719,
  'lon': -74.063903,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1451628087,
  'lat': 4.6358633,
  'lon': -74.0824368,
  'tags': {'amenity': 'cafe',
   'brand': 'Tostao’',
   'brand:wikidata': 'Q60632476',
   'building': 'university',
   'cuisine': 'coffee_shop',
   'name': 'Tostao’',
   'name:es': 'Tostao’'}},
 {'type': 'node',
  'id': 1459466513,
  'lat': 4.6717245,
  'lon': -74.0591688,
  'tags': {'amenity': 'cafe', 'name': 'Las Cafetales'}},
 {'type': 'node',
  'id': 1459468413,
  'lat': 4.600109,
  'lon': -74.0706196,
  'tags': {'amenity': 'cafe', 'name': 'Rock al Horno'}},
 {'type': 'node',
  'id': 1459468418,
  'lat': 4.6005428,
  'lon': -74.0700032,
  'tags': {'amenity': 'cafe', 'name': 'Hibrido', 'name:es': 'Hibrido'}},
 {'type': 'node',
  'id': 1460556480,
  'lat': 4.5989831,
  'lon': -74.0705608,
  'tags': {'amenity': 'cafe', 'name': 'Cafe del sol'}},
 {'type': 'node',
  'id': 1586401453,
  'lat': 4.7482454,
  'lon': -74.0968103,
  'tags': {'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name': 'Cafe OMA'}},
 {'type': 'node',
  'id': 1595604250,
  'lat': 4.5040339,
  'lon': -74.1149679,
  'tags': {'amenity': 'cafe', 'name': 'Panadería y Cafeteria'}},
 {'type': 'node',
  'id': 1595608094,
  'lat': 4.5049805,
  'lon': -74.115051,
  'tags': {'amenity': 'cafe', 'name': 'Panadería'}},
 {'type': 'node',
  'id': 1615705927,
  'lat': 4.6467244,
  'lon': -74.0601618,
  'tags': {'addr:city': 'Bogotá',
   'addr:full': 'Cra 7 # 61-52',
   'amenity': 'cafe',
   'brand': 'Tostao’',
   'brand:wikidata': 'Q60632476',
   'cuisine': 'coffee_shop',
   'internet_access': 'wlan',
   'internet_access:fee': 'no',
   'name': 'Tostao’',
   'name:es': 'Tostao’',
   'operator': 'Café Juan Valdez',
   'shop': 'beverages',
   'smoking': 'yes',
   'wheelchair': 'no'}},
 {'type': 'node',
  'id': 1615705933,
  'lat': 4.6453457,
  'lon': -74.0575346,
  'tags': {'addr:city': 'Bogotá D.C.',
   'addr:housenumber': '61-42',
   'addr:street': 'Carrera 3B',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 1624309379,
  'lat': 4.6325899,
  'lon': -74.0746713,
  'tags': {'addr:housename': 'Calle 42',
   'addr:housenumber': '22-54',
   'amenity': 'cafe',
   'cuisine': 'spanish',
   'name': 'El Cafetín de la Soledad',
   'wifi': 'free'}},
 {'type': 'node',
  'id': 1634612585,
  'lat': 4.7413943,
  'lon': -74.0345859,
  'tags': {'amenity': 'cafe',
   'brand': 'Tostao’',
   'brand:wikidata': 'Q60632476',
   'cuisine': 'coffee_shop',
   'name': 'Tostao’',
   'name:es': 'Tostao’',
   'official_name': 'TOSTAO’ Café & Pan',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 1659534257,
  'lat': 4.69782,
  'lon': -74.0477571,
  'tags': {'amenity': 'cafe',
   'name': 'Juan Valdez Cafe',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 1659534258,
  'lat': 4.6978435,
  'lon': -74.0478151,
  'tags': {'amenity': 'cafe',
   'cuisine': 'pasteleria',
   'name': 'amínta',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 1660844410,
  'lat': 4.6974846,
  'lon': -74.0329179,
  'tags': {'amenity': 'cafe', 'name': 'Doña DIcha', 'wheelchair': 'no'}},
 {'type': 'node',
  'id': 1661478291,
  'lat': 4.6784727,
  'lon': -74.0465928,
  'tags': {'amenity': 'cafe',
   'cuisine': 'coffee_shop',
   'internet_access': 'wlan',
   'name': 'El Deseo'}},
 {'type': 'node',
  'id': 1661487943,
  'lat': 4.6801863,
  'lon': -74.0482048,
  'tags': {'amenity': 'cafe', 'name': 'Diletto', 'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 1824986067,
  'lat': 4.6660569,
  'lon': -74.0556673,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'yes'}},
 {'type': 'node',
  'id': 1855061085,
  'lat': 4.6636139,
  'lon': -74.0579561,
  'tags': {'addr:street': 'Calle 77',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'source': 'Kaart Ground Survey 2017',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 1882851241,
  'lat': 4.6276756,
  'lon': -74.063023,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 1882851262,
  'lat': 4.6265561,
  'lon': -74.065059,
  'tags': {'amenity': 'cafe', 'description': 'CafeteriaPiso2'}},
 {'type': 'node',
  'id': 1882851269,
  'lat': 4.6268031,
  'lon': -74.0636183,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1882851275,
  'lat': 4.62695,
  'lon': -74.0650021,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1882851292,
  'lat': 4.628034,
  'lon': -74.0643982,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1882851302,
  'lat': 4.6286548,
  'lon': -74.0640631,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1934487139,
  'lat': 4.6337398,
  'lon': -74.0855876,
  'tags': {'amenity': 'cafe',
   'building': 'university',
   'name': 'Cafeteria Geologia'}},
 {'type': 'node',
  'id': 1940810948,
  'lat': 4.6448735,
  'lon': -74.1657269,
  'tags': {'amenity': 'cafe', 'name': 'Panadería Natys'}},
 {'type': 'node',
  'id': 1986116926,
  'lat': 4.718695,
  'lon': -74.035439,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1986209954,
  'lat': 4.7201407,
  'lon': -74.0380722,
  'tags': {'addr:street': 'Calle 140',
   'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'source': 'Kaart Ground Survey 2017',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/'}},
 {'type': 'node',
  'id': 2021967796,
  'lat': 4.6007912,
  'lon': -74.0651978,
  'tags': {'addr:housename': 'Bloque N, primer piso',
   'addr:place': 'Universidad de los Andes',
   'amenity': 'cafe',
   'diet:vegetarian': 'yes',
   'internet_access': 'wlan',
   'internet_access:fee': 'no',
   'name': 'Cafeteria Central',
   'opening_hours': 'Mo-Fr 07:00-20:00',
   'opening_hours:es': 'Lu-Vi 7:00-20:00',
   'operator': 'Dialimentos',
   'smoking': 'no',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-dialimentos',
   'wheelchair': 'yes',
   'wifi': 'yes'}},
 {'type': 'node',
  'id': 2021979046,
  'lat': 4.6007113,
  'lon': -74.0660095,
  'tags': {'addr:housename': 'Bloque z, galpón',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023673410,
  'lat': 4.601636,
  'lon': -74.0645381,
  'tags': {'addr:housename': 'Bloque V',
   'amenity': 'cafe',
   'internet_access': 'wlan',
   'name': 'Café Kaldivia',
   'url': 'https://campusinfo.uniandes.edu.co/es/recursos/edificios/elcampito',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Alimentos-Spress',
   'wheelchair': 'no',
   'wifi': 'yes'}},
 {'type': 'node',
  'id': 2023682954,
  'lat': 4.6018583,
  'lon': -74.0653355,
  'tags': {'addr:housename': 'Plazoleta Lleras',
   'amenity': 'cafe',
   'name': 'Las Monas',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Alimentos-Spress'}},
 {'type': 'node',
  'id': 2023685769,
  'lat': 4.6003182,
  'lon': -74.0650277,
  'tags': {'addr:housename': 'Bloque Q terraza',
   'amenity': 'cafe',
   'name': 'La Frutería',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-L-Fruiterie'}},
 {'type': 'node',
  'id': 2023692417,
  'lat': 4.6024274,
  'lon': -74.0655533,
  'tags': {'addr:housename': 'Bloque z, galpón',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023697512,
  'lat': 4.6016681,
  'lon': -74.0642122,
  'tags': {'addr:housename': 'Plazoleta Richard',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023701871,
  'lat': 4.6027797,
  'lon': -74.0645256,
  'tags': {'addr:housename': 'Biblioteca General, 3er piso',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'level': '3',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023718129,
  'lat': 4.6028332,
  'lon': -74.0647332,
  'tags': {'addr:housename': 'Edificio Mario Laserna, punto central, quinto piso',
   'amenity': 'cafe',
   'level': '5',
   'name': 'Cascabel',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Cascabel'}},
 {'type': 'node',
  'id': 2023726080,
  'lat': 4.6026038,
  'lon': -74.0663929,
  'tags': {'addr:housename': 'Bloque AU, primer piso',
   'amenity': 'cafe',
   'name': 'Cascabel',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Cascabel'}},
 {'type': 'node',
  'id': 2023735292,
  'lat': 4.6027455,
  'lon': -74.0645958,
  'tags': {'addr:housename': 'Edificio Mario Laserna, puntos laterales, 5to piso',
   'amenity': 'cafe',
   'level': '5',
   'name': 'GRATTO',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Gratto'}},
 {'type': 'node',
  'id': 2023742114,
  'lat': 4.6000212,
  'lon': -74.0628309,
  'tags': {'addr:housename': 'Centro Deportivo, segundo piso',

In [ ]:
elements_cafes = data_cafes["elements"]
elements_cafes

[{'type': 'node',
  'id': 265501503,
  'lat': 4.6396774,
  'lon': -74.0630225,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/'}},
 {'type': 'node',
  'id': 265501535,
  'lat': 4.6402868,
  'lon': -74.0628995,
  'tags': {'addr:street': 'Avenida Carrera 7',
   'amenity': 'cafe',
   'name': 'La Cafeteria',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 340429454,
  'lat': 4.6761001,
  'lon': -74.0475614,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'opening_hours': 'Mo-Su 07:00-22:00',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 368176844,
  'lat': 4.6504734,
  'lon': -74.0917405,
  'tags': {'amenity': 'cafe', 'name': 'Salon de Té F&W'}},
 {'type': 'node',
  'id': 405236743,
  'lat': 4.7070904,
  'lon': -74.0581185,
  'tags': {'amenity': 'cafe',
   'brand': "Pan Pa' Ya!",
   'brand:wikidata': 'Q131744932',
   'level': '0',
   'name': "Pan Pa' Ya!",
   'payment:cards': 'yes',
   'payment:cash': 'yes',
   'service:electricity': 'no',
   'shop': 'bakery',
   'smoking': 'no',
   'wheelchair': 'yes'}},
 {'type': 'node',
  'id': 460405530,
  'lat': 4.6580768,
  'lon': -74.1118237,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 485363102,
  'lat': 4.6824213,
  'lon': -74.0488925,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 485536579,
  'lat': 4.7267619,
  'lon': -74.0357369,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 494767144,
  'lat': 4.7614606,
  'lon': -74.0437824,
  'tags': {'amenity': 'cafe', 'name': 'El marinero'}},
 {'type': 'node',
  'id': 499109158,
  'lat': 4.7717566,
  'lon': -74.0423748,
  'tags': {'amenity': 'cafe', 'name': 'On the run'}},
 {'type': 'node',
  'id': 501789966,
  'lat': 4.6668322,
  'lon': -74.0525611,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'no'}},
 {'type': 'node',
  'id': 505075470,
  'lat': 4.6979174,
  'lon': -74.0691586,
  'tags': {'addr:street': 'Avenida Suba',
   'amenity': 'cafe',
   'name': 'Autopan',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 506310009,
  'lat': 4.7387233,
  'lon': -74.0443946,
  'tags': {'amenity': 'cafe', 'name': 'Cafe internet'}},
 {'type': 'node',
  'id': 506542813,
  'lat': 4.7290096,
  'lon': -74.0408665,
  'tags': {'addr:street': 'Avenida Cedritos',
   'amenity': 'cafe',
   'brand': "Pan Pa' Ya!",
   'brand:wikidata': 'Q131744932',
   'name': "Pan Pa' Ya!",
   'shop': 'bakery',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 517123861,
  'lat': 4.6910866,
  'lon': -74.1003074,
  'tags': {'amenity': 'cafe', 'name': 'Festytortas'}},
 {'type': 'node',
  'id': 529748669,
  'lat': 4.6430295,
  'lon': -74.101606,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 595598570,
  'lat': 4.6703265,
  'lon': -74.1062994,
  'tags': {'amenity': 'cafe', 'name': 'Pasteleria Santander'}},
 {'type': 'node',
  'id': 600238725,
  'lat': 4.701068,
  'lon': -74.115428,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 601254785,
  'lat': 4.6425553,
  'lon': -74.1348505,
  'tags': {'addr:city': 'Kennedy',
   'addr:street': 'Carrera 72A',
   'amenity': 'cafe',
   'name': 'Meridianos Pan y Cafe',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 601255096,
  'lat': 4.6577458,
  'lon': -74.1182451,
  'tags': {'amenity': 'cafe', 'name': 'Pan Suizo'}},
 {'type': 'node',
  'id': 605667595,
  'lat': 4.6503058,
  'lon': -74.0870628,
  'tags': {'amenity': 'cafe', 'name': 'Picos y Cafe'}},
 {'type': 'node',
  'id': 614660111,
  'lat': 4.7281189,
  'lon': -74.0648271,
  'tags': {'amenity': 'cafe', 'name': 'Juan Valdés'}},
 {'type': 'node',
  'id': 616522538,
  'lat': 4.7109718,
  'lon': -74.140064,
  'tags': {'addr:street': 'Calle 64',
   'amenity': 'cafe',
   'name': 'Monserrate',
   'shop': 'bakery',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 662221657,
  'lat': 4.6836004,
  'lon': -74.0804715,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 666688399,
  'lat': 4.6178721,
  'lon': -74.1281357,
  'tags': {'amenity': 'cafe', 'name': 'Terranova'}},
 {'type': 'node',
  'id': 679776620,
  'lat': 4.5718378,
  'lon': -74.1023154,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 695229274,
  'lat': 4.7549816,
  'lon': -74.0465828,
  'tags': {'addr:city': 'Bogota',
   'addr:country': 'CO',
   'addr:housenumber': '45-9',
   'addr:street': 'Calle 174A',
   'amenity': 'cafe',
   'brand': 'Tostao'}},
 {'type': 'node',
  'id': 756685866,
  'lat': 4.52194,
  'lon': -74.1212078,
  'tags': {'amenity': 'cafe', 'name': 'WilPan'}},
 {'type': 'node',
  'id': 775392658,
  'lat': 4.6880551,
  'lon': -74.0692988,
  'tags': {'addr:street': 'Calle 98',
   'amenity': 'cafe',
   'name': 'Limbapan',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 822152787,
  'lat': 4.6336939,
  'lon': -74.102892,
  'tags': {'amenity': 'cafe', 'name': 'On the Run'}},
 {'type': 'node',
  'id': 849023912,
  'lat': 4.6678858,
  'lon': -74.0538027,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 859121163,
  'lat': 4.7230014,
  'lon': -74.0679086,
  'tags': {'amenity': 'cafe', 'name': 'Wilsón'}},
 {'type': 'node',
  'id': 859648400,
  'lat': 4.6643983,
  'lon': -74.0613895,
  'tags': {'amenity': 'cafe', 'wheelchair': 'no'}},
 {'type': 'node',
  'id': 878234750,
  'lat': 4.6571319,
  'lon': -74.0560636,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/'}},
 {'type': 'node',
  'id': 954696710,
  'lat': 4.6032593,
  'lon': -74.0662201,
  'tags': {'amenity': 'cafe', 'name': 'Doña Blanca'}},
 {'type': 'node',
  'id': 1040448121,
  'lat': 4.6937664,
  'lon': -74.0663162,
  'tags': {'amenity': 'cafe', 'name': 'Salzig'}},
 {'type': 'node',
  'id': 1062675225,
  'lat': 4.6661654,
  'lon': -74.1260495,
  'tags': {'addr:street': 'Carrera 82',
   'amenity': 'cafe',
   'name': 'Pan de Oro',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 1106833491,
  'lat': 4.6034563,
  'lon': -74.0725164,
  'tags': {'amenity': 'cafe', 'name': 'Oma'}},
 {'type': 'node',
  'id': 1117605036,
  'lat': 4.6302368,
  'lon': -74.0748324,
  'tags': {'addr:city': 'Bogotá',
   'addr:street': 'Carrera 24',
   'amenity': 'cafe',
   'name': 'Panadería Arlequin',
   'source': 'Kaart Ground Survey 2017'}},
 {'type': 'node',
  'id': 1118998288,
  'lat': 4.6008511,
  'lon': -74.0682011,
  'tags': {'addr:housenumber': '2-51',
   'addr:street': 'Calle 17',
   'amenity': 'cafe',
   'internet_access': 'yes',
   'name': 'La Redada Miscelánea Cultural',
   'phone': '571-3422107',
   'website': 'www.laredada.org'}},
 {'type': 'node',
  'id': 1123520521,
  'lat': 4.7559209,
  'lon': -74.0516087,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1123520542,
  'lat': 4.7558567,
  'lon': -74.0506538,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1193385201,
  'lat': 4.6570346,
  'lon': -74.0578146,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 1201598234,
  'lat': 4.6309608,
  'lon': -74.0667937,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 1268313156,
  'lat': 4.6090909,
  'lon': -74.0688278,
  'tags': {'addr:city': 'Bogotá',
   'addr:street': 'Calle 24',
   'amenity': 'cafe',
   'cuisine': 'Café_de_orígen',
   'internet_access': 'yes',
   'name': 'Café Recoleta',
   'smoking': 'no'}},
 {'type': 'node',
  'id': 1277994075,
  'lat': 4.635117,
  'lon': -74.0750056,
  'tags': {'amenity': 'cafe', 'cuisine': 'international', 'name': 'San Cafe'}},
 {'type': 'node',
  'id': 1336170374,
  'lat': 4.5683626,
  'lon': -74.0970217,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1383986709,
  'lat': 4.6272621,
  'lon': -74.0625932,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1384008514,
  'lat': 4.6280968,
  'lon': -74.0632359,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1384008521,
  'lat': 4.628759,
  'lon': -74.062728,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1384008566,
  'lat': 4.630719,
  'lon': -74.063903,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1451628087,
  'lat': 4.6358633,
  'lon': -74.0824368,
  'tags': {'amenity': 'cafe',
   'brand': 'Tostao’',
   'brand:wikidata': 'Q60632476',
   'building': 'university',
   'cuisine': 'coffee_shop',
   'name': 'Tostao’',
   'name:es': 'Tostao’'}},
 {'type': 'node',
  'id': 1459466513,
  'lat': 4.6717245,
  'lon': -74.0591688,
  'tags': {'amenity': 'cafe', 'name': 'Las Cafetales'}},
 {'type': 'node',
  'id': 1459468413,
  'lat': 4.600109,
  'lon': -74.0706196,
  'tags': {'amenity': 'cafe', 'name': 'Rock al Horno'}},
 {'type': 'node',
  'id': 1459468418,
  'lat': 4.6005428,
  'lon': -74.0700032,
  'tags': {'amenity': 'cafe', 'name': 'Hibrido', 'name:es': 'Hibrido'}},
 {'type': 'node',
  'id': 1460556480,
  'lat': 4.5989831,
  'lon': -74.0705608,
  'tags': {'amenity': 'cafe', 'name': 'Cafe del sol'}},
 {'type': 'node',
  'id': 1586401453,
  'lat': 4.7482454,
  'lon': -74.0968103,
  'tags': {'amenity': 'cafe', 'cuisine': 'coffee_shop', 'name': 'Cafe OMA'}},
 {'type': 'node',
  'id': 1595604250,
  'lat': 4.5040339,
  'lon': -74.1149679,
  'tags': {'amenity': 'cafe', 'name': 'Panadería y Cafeteria'}},
 {'type': 'node',
  'id': 1595608094,
  'lat': 4.5049805,
  'lon': -74.115051,
  'tags': {'amenity': 'cafe', 'name': 'Panadería'}},
 {'type': 'node',
  'id': 1615705927,
  'lat': 4.6467244,
  'lon': -74.0601618,
  'tags': {'addr:city': 'Bogotá',
   'addr:full': 'Cra 7 # 61-52',
   'amenity': 'cafe',
   'brand': 'Tostao’',
   'brand:wikidata': 'Q60632476',
   'cuisine': 'coffee_shop',
   'internet_access': 'wlan',
   'internet_access:fee': 'no',
   'name': 'Tostao’',
   'name:es': 'Tostao’',
   'operator': 'Café Juan Valdez',
   'shop': 'beverages',
   'smoking': 'yes',
   'wheelchair': 'no'}},
 {'type': 'node',
  'id': 1615705933,
  'lat': 4.6453457,
  'lon': -74.0575346,
  'tags': {'addr:city': 'Bogotá D.C.',
   'addr:housenumber': '61-42',
   'addr:street': 'Carrera 3B',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 1624309379,
  'lat': 4.6325899,
  'lon': -74.0746713,
  'tags': {'addr:housename': 'Calle 42',
   'addr:housenumber': '22-54',
   'amenity': 'cafe',
   'cuisine': 'spanish',
   'name': 'El Cafetín de la Soledad',
   'wifi': 'free'}},
 {'type': 'node',
  'id': 1634612585,
  'lat': 4.7413943,
  'lon': -74.0345859,
  'tags': {'amenity': 'cafe',
   'brand': 'Tostao’',
   'brand:wikidata': 'Q60632476',
   'cuisine': 'coffee_shop',
   'name': 'Tostao’',
   'name:es': 'Tostao’',
   'official_name': 'TOSTAO’ Café & Pan',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 1659534257,
  'lat': 4.69782,
  'lon': -74.0477571,
  'tags': {'amenity': 'cafe',
   'name': 'Juan Valdez Cafe',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 1659534258,
  'lat': 4.6978435,
  'lon': -74.0478151,
  'tags': {'amenity': 'cafe',
   'cuisine': 'pasteleria',
   'name': 'amínta',
   'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 1660844410,
  'lat': 4.6974846,
  'lon': -74.0329179,
  'tags': {'amenity': 'cafe', 'name': 'Doña DIcha', 'wheelchair': 'no'}},
 {'type': 'node',
  'id': 1661478291,
  'lat': 4.6784727,
  'lon': -74.0465928,
  'tags': {'amenity': 'cafe',
   'cuisine': 'coffee_shop',
   'internet_access': 'wlan',
   'name': 'El Deseo'}},
 {'type': 'node',
  'id': 1661487943,
  'lat': 4.6801863,
  'lon': -74.0482048,
  'tags': {'amenity': 'cafe', 'name': 'Diletto', 'wheelchair': 'limited'}},
 {'type': 'node',
  'id': 1824986067,
  'lat': 4.6660569,
  'lon': -74.0556673,
  'tags': {'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/',
   'wheelchair': 'yes'}},
 {'type': 'node',
  'id': 1855061085,
  'lat': 4.6636139,
  'lon': -74.0579561,
  'tags': {'addr:street': 'Calle 77',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'source': 'Kaart Ground Survey 2017',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 1882851241,
  'lat': 4.6276756,
  'lon': -74.063023,
  'tags': {'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'name': 'Café OMA',
   'takeaway': 'yes',
   'website': 'https://www.cafeoma.com/'}},
 {'type': 'node',
  'id': 1882851262,
  'lat': 4.6265561,
  'lon': -74.065059,
  'tags': {'amenity': 'cafe', 'description': 'CafeteriaPiso2'}},
 {'type': 'node',
  'id': 1882851269,
  'lat': 4.6268031,
  'lon': -74.0636183,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1882851275,
  'lat': 4.62695,
  'lon': -74.0650021,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1882851292,
  'lat': 4.628034,
  'lon': -74.0643982,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1882851302,
  'lat': 4.6286548,
  'lon': -74.0640631,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1934487139,
  'lat': 4.6337398,
  'lon': -74.0855876,
  'tags': {'amenity': 'cafe',
   'building': 'university',
   'name': 'Cafeteria Geologia'}},
 {'type': 'node',
  'id': 1940810948,
  'lat': 4.6448735,
  'lon': -74.1657269,
  'tags': {'amenity': 'cafe', 'name': 'Panadería Natys'}},
 {'type': 'node',
  'id': 1986116926,
  'lat': 4.718695,
  'lon': -74.035439,
  'tags': {'amenity': 'cafe'}},
 {'type': 'node',
  'id': 1986209954,
  'lat': 4.7201407,
  'lon': -74.0380722,
  'tags': {'addr:street': 'Calle 140',
   'amenity': 'cafe',
   'brand': 'Juan Valdez Café',
   'brand:wikidata': 'Q6301102',
   'brand:wikipedia': 'en:Juan Valdez Café',
   'cuisine': 'coffee_shop',
   'name': 'Juan Valdez Café',
   'name:es': 'Juan Valdez Café',
   'shop': 'coffee',
   'source': 'Kaart Ground Survey 2017',
   'takeaway': 'yes',
   'website': 'https://juanvaldez.com/'}},
 {'type': 'node',
  'id': 2021967796,
  'lat': 4.6007912,
  'lon': -74.0651978,
  'tags': {'addr:housename': 'Bloque N, primer piso',
   'addr:place': 'Universidad de los Andes',
   'amenity': 'cafe',
   'diet:vegetarian': 'yes',
   'internet_access': 'wlan',
   'internet_access:fee': 'no',
   'name': 'Cafeteria Central',
   'opening_hours': 'Mo-Fr 07:00-20:00',
   'opening_hours:es': 'Lu-Vi 7:00-20:00',
   'operator': 'Dialimentos',
   'smoking': 'no',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-dialimentos',
   'wheelchair': 'yes',
   'wifi': 'yes'}},
 {'type': 'node',
  'id': 2021979046,
  'lat': 4.6007113,
  'lon': -74.0660095,
  'tags': {'addr:housename': 'Bloque z, galpón',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023673410,
  'lat': 4.601636,
  'lon': -74.0645381,
  'tags': {'addr:housename': 'Bloque V',
   'amenity': 'cafe',
   'internet_access': 'wlan',
   'name': 'Café Kaldivia',
   'url': 'https://campusinfo.uniandes.edu.co/es/recursos/edificios/elcampito',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Alimentos-Spress',
   'wheelchair': 'no',
   'wifi': 'yes'}},
 {'type': 'node',
  'id': 2023682954,
  'lat': 4.6018583,
  'lon': -74.0653355,
  'tags': {'addr:housename': 'Plazoleta Lleras',
   'amenity': 'cafe',
   'name': 'Las Monas',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Alimentos-Spress'}},
 {'type': 'node',
  'id': 2023685769,
  'lat': 4.6003182,
  'lon': -74.0650277,
  'tags': {'addr:housename': 'Bloque Q terraza',
   'amenity': 'cafe',
   'name': 'La Frutería',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-L-Fruiterie'}},
 {'type': 'node',
  'id': 2023692417,
  'lat': 4.6024274,
  'lon': -74.0655533,
  'tags': {'addr:housename': 'Bloque z, galpón',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023697512,
  'lat': 4.6016681,
  'lon': -74.0642122,
  'tags': {'addr:housename': 'Plazoleta Richard',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023701871,
  'lat': 4.6027797,
  'lon': -74.0645256,
  'tags': {'addr:housename': 'Biblioteca General, 3er piso',
   'amenity': 'cafe',
   'brand': 'Café OMA',
   'brand:wikidata': 'Q108929487',
   'cuisine': 'coffee_shop',
   'level': '3',
   'name': 'Café OMA',
   'takeaway': 'yes'}},
 {'type': 'node',
  'id': 2023718129,
  'lat': 4.6028332,
  'lon': -74.0647332,
  'tags': {'addr:housename': 'Edificio Mario Laserna, punto central, quinto piso',
   'amenity': 'cafe',
   'level': '5',
   'name': 'Cascabel',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Cascabel'}},
 {'type': 'node',
  'id': 2023726080,
  'lat': 4.6026038,
  'lon': -74.0663929,
  'tags': {'addr:housename': 'Bloque AU, primer piso',
   'amenity': 'cafe',
   'name': 'Cascabel',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Cascabel'}},
 {'type': 'node',
  'id': 2023735292,
  'lat': 4.6027455,
  'lon': -74.0645958,
  'tags': {'addr:housename': 'Edificio Mario Laserna, puntos laterales, 5to piso',
   'amenity': 'cafe',
   'level': '5',
   'name': 'GRATTO',
   'website': 'https://direccionadministrativa.uniandes.edu.co/Servicios/Cafeterias/Listado-de-precios-Gratto'}},
 {'type': 'node',
  'id': 2023742114,
  'lat': 4.6000212,
  'lon': -74.0628309,
  'tags': {'addr:housename': 'Centro Deportivo, segundo piso',

In [ ]:
cafeterias = []
for element in elements_cafes:
    if "lat" in element and "lon" in element:
        cafeterias.append({
            "name": element["tags"].get("name", "Desconocido"),
            "lat": element["lat"],
            "lon": element["lon"]
        })

print(cafeterias)

[{'name': 'Juan Valdez Café', 'lat': 4.6396774, 'lon': -74.0630225}, {'name': 'La Cafeteria', 'lat': 4.6402868, 'lon': -74.0628995}, {'name': 'Juan Valdez Café', 'lat': 4.6761001, 'lon': -74.0475614}, {'name': 'Salon de Té F&W', 'lat': 4.6504734, 'lon': -74.0917405}, {'name': "Pan Pa' Ya!", 'lat': 4.7070904, 'lon': -74.0581185}, {'name': 'Desconocido', 'lat': 4.6580768, 'lon': -74.1118237}, {'name': 'Café OMA', 'lat': 4.6824213, 'lon': -74.0488925}, {'name': 'Desconocido', 'lat': 4.7267619, 'lon': -74.0357369}, {'name': 'El marinero', 'lat': 4.7614606, 'lon': -74.0437824}, {'name': 'On the run', 'lat': 4.7717566, 'lon': -74.0423748}, {'name': 'Juan Valdez Café', 'lat': 4.6668322, 'lon': -74.0525611}, {'name': 'Autopan', 'lat': 4.6979174, 'lon': -74.0691586}, {'name': 'Cafe internet', 'lat': 4.7387233, 'lon': -74.0443946}, {'name': "Pan Pa' Ya!", 'lat': 4.7290096, 'lon': -74.0408665}, {'name': 'Festytortas', 'lat': 4.6910866, 'lon': -74.1003074}, {'name': 'Desconocido', 'lat': 4.6430295, 'lon': -74.101606}, {'name': 'Pasteleria Santander', 'lat': 4.6703265, 'lon': -74.1062994}, {'name': 'Café OMA', 'lat': 4.701068, 'lon': -74.115428}, {'name': 'Meridianos Pan y Cafe', 'lat': 4.6425553, 'lon': -74.1348505}, {'name': 'Pan Suizo', 'lat': 4.6577458, 'lon': -74.1182451}, {'name': 'Picos y Cafe', 'lat': 4.6503058, 'lon': -74.0870628}, {'name': 'Juan Valdés', 'lat': 4.7281189, 'lon': -74.0648271}, {'name': 'Monserrate', 'lat': 4.7109718, 'lon': -74.140064}, {'name': 'Café OMA', 'lat': 4.6836004, 'lon': -74.0804715}, {'name': 'Terranova', 'lat': 4.6178721, 'lon': -74.1281357}, {'name': 'Desconocido', 'lat': 4.5718378, 'lon': -74.1023154}, {'name': 'Desconocido', 'lat': 4.7549816, 'lon': -74.0465828}, {'name': 'WilPan', 'lat': 4.52194, 'lon': -74.1212078}, {'name': 'Limbapan', 'lat': 4.6880551, 'lon': -74.0692988}, {'name': 'On the Run', 'lat': 4.6336939, 'lon': -74.102892}, {'name': 'Café OMA', 'lat': 4.6678858, 'lon': -74.0538027}, {'name': 'Wilsón', 'lat': 4.7230014, 'lon': -74.0679086}, {'name': 'Desconocido', 'lat': 4.6643983, 'lon': -74.0613895}, {'name': 'Juan Valdez Café', 'lat': 4.6571319, 'lon': -74.0560636}, {'name': 'Doña Blanca', 'lat': 4.6032593, 'lon': -74.0662201}, {'name': 'Salzig', 'lat': 4.6937664, 'lon': -74.0663162}, {'name': 'Pan de Oro', 'lat': 4.6661654, 'lon': -74.1260495}, {'name': 'Oma', 'lat': 4.6034563, 'lon': -74.0725164}, {'name': 'Panadería Arlequin', 'lat': 4.6302368, 'lon': -74.0748324}, {'name': 'La Redada Miscelánea Cultural', 'lat': 4.6008511, 'lon': -74.0682011}, {'name': 'Desconocido', 'lat': 4.7559209, 'lon': -74.0516087}, {'name': 'Desconocido', 'lat': 4.7558567, 'lon': -74.0506538}, {'name': 'Café OMA', 'lat': 4.6570346, 'lon': -74.0578146}, {'name': 'Café OMA', 'lat': 4.6309608, 'lon': -74.0667937}, {'name': 'Café Recoleta', 'lat': 4.6090909, 'lon': -74.0688278}, {'name': 'San Cafe', 'lat': 4.635117, 'lon': -74.0750056}, {'name': 'Desconocido', 'lat': 4.5683626, 'lon': -74.0970217}, {'name': 'Desconocido', 'lat': 4.6272621, 'lon': -74.0625932}, {'name': 'Desconocido', 'lat': 4.6280968, 'lon': -74.0632359}, {'name': 'Desconocido', 'lat': 4.628759, 'lon': -74.062728}, {'name': 'Desconocido', 'lat': 4.630719, 'lon': -74.063903}, {'name': 'Tostao’', 'lat': 4.6358633, 'lon': -74.0824368}, {'name': 'Las Cafetales', 'lat': 4.6717245, 'lon': -74.0591688}, {'name': 'Rock al Horno', 'lat': 4.600109, 'lon': -74.0706196}, {'name': 'Hibrido', 'lat': 4.6005428, 'lon': -74.0700032}, {'name': 'Cafe del sol', 'lat': 4.5989831, 'lon': -74.0705608}, {'name': 'Cafe OMA', 'lat': 4.7482454, 'lon': -74.0968103}, {'name': 'Panadería y Cafeteria', 'lat': 4.5040339, 'lon': -74.1149679}, {'name': 'Panadería', 'lat': 4.5049805, 'lon': -74.115051}, {'name': 'Tostao’', 'lat': 4.6467244, 'lon': -74.0601618}, {'name': 'Café OMA', 'lat': 4.6453457, 'lon': -74.0575346}, {'name': 'El Cafetín de la Soledad', 'lat': 4.6325899, 'lon': -74.0746713}, {'name': 'Tostao’', 'lat': 4.7413943, 'lon': -74.0345859}, {'name': 'Juan Valdez Cafe', 'lat': 4.69782, 'lon': -74.0477571}, {'name': 'amínta', 'lat': 4.6978435, 'lon': -74.0478151}, {'name': 'Doña DIcha', 'lat': 4.6974846, 'lon': -74.0329179}, {'name': 'El Deseo', 'lat': 4.6784727, 'lon': -74.0465928}, {'name': 'Diletto', 'lat': 4.6801863, 'lon': -74.0482048}, {'name': 'Juan Valdez Café', 'lat': 4.6660569, 'lon': -74.0556673}, {'name': 'Café OMA', 'lat': 4.6636139, 'lon': -74.0579561}, {'name': 'Café OMA', 'lat': 4.6276756, 'lon': -74.063023}, {'name': 'Desconocido', 'lat': 4.6265561, 'lon': -74.065059}, {'name': 'Desconocido', 'lat': 4.6268031, 'lon': -74.0636183}, {'name': 'Desconocido', 'lat': 4.62695, 'lon': -74.0650021}, {'name': 'Desconocido', 'lat': 4.628034, 'lon': -74.0643982}, {'name': 'Desconocido', 'lat': 4.6286548, 'lon': -74.0640631}, {'name': 'Cafeteria Geologia', 'lat': 4.6337398, 'lon': -74.0855876}, {'name': 'Panadería Natys', 'lat': 4.6448735, 'lon': -74.1657269}, {'name': 'Desconocido', 'lat': 4.718695, 'lon': -74.035439}, {'name': 'Juan Valdez Café', 'lat': 4.7201407, 'lon': -74.0380722}, {'name': 'Cafeteria Central', 'lat': 4.6007912, 'lon': -74.0651978}, {'name': 'Café OMA', 'lat': 4.6007113, 'lon': -74.0660095}, {'name': 'Café Kaldivia', 'lat': 4.601636, 'lon': -74.0645381}, {'name': 'Las Monas', 'lat': 4.6018583, 'lon': -74.0653355}, {'name': 'La Frutería', 'lat': 4.6003182, 'lon': -74.0650277}, {'name': 'Café OMA', 'lat': 4.6024274, 'lon': -74.0655533}, {'name': 'Café OMA', 'lat': 4.6016681, 'lon': -74.0642122}, {'name': 'Café OMA', 'lat': 4.6027797, 'lon': -74.0645256}, {'name': 'Cascabel', 'lat': 4.6028332, 'lon': -74.0647332}, {'name': 'Cascabel', 'lat': 4.6026038, 'lon': -74.0663929}, {'name': 'GRATTO', 'lat': 4.6027455, 'lon': -74.0645958}, {'name': 'Oma', 'lat': 4.6000212, 'lon': -74.0628309}, {'name': 'Explora Hostel', 'lat': 4.5986425, 'lon': -74.0703923}, {'name': 'El gato gris', 'lat': 4.5970383, 'lon': -74.0696065}, {'name': 'Desconocido', 'lat': 4.6437983, 'lon': -74.0649454}, {'name': 'Cafetería El Cotidiano', 'lat': 4.6299118, 'lon': -74.0640645}, {'name': 'Subway Basicas', 'lat': 4.629289, 'lon': -74.064331}, {'name': 'Lachoco Latera', 'lat': 4.6130271, 'lon': -74.0666541}, {'name': 'Juan Valdez - Skandia', 'lat': 4.6959627, 'lon': -74.0501952}, {'name': 'Cafetería de Ciencias Humanas', 'lat': 4.6345117, 'lon': -74.083933}, {'name': 'Bitcoin Muffin', 'lat': 4.6737386, 'lon': -74.1201082}, {'name': 'Árbol del Pan', 'lat': 4.6488241, 'lon': -74.0562021}, {'name': 'Juan Valdez Café', 'lat': 4.6983005, 'lon': -74.1411693}, {'name': 'Juan Valdez Café', 'lat': 4.6010864, 'lon': -74.0700845}, {'name': 'Cafeteria Sabrosuras', 'lat': 4.6317612, 'lon': -74.0848903}, {'name': 'Cafeteria y Panaderia Isabella', 'lat': 4.6307692, 'lon': -74.0816497}, {'name': 'Postres Magolita', 'lat': 4.633301, 'lon': -74.0894881}, {'name': 'Café OMA', 'lat': 4.7127526, 'lon': -74.0341796}, {'name': 'Panadería', 'lat': 4.6461646, 'lon': -74.1640535}, {'name': 'Juan Valdez Origenes', 'lat': 4.6522542, 'lon': -74.0559027}, {'name': 'Varietale', 'lat': 4.6287698, 'lon': -74.0663633}, {'name': 'Fruteria Tropical', 'lat': 4.7427925, 'lon': -74.1084954}, {'name': 'Desconocido', 'lat': 4.5966779, 'lon': -74.1365378}, {'name': 'Rustico cafe bar', 'lat': 4.631659, 'lon': -74.0654932}, {'name': 'Cigarreria y Cafetería Variedade', 'lat': 4.6278304, 'lon': -74.0687611}, {'name': 'wimpys', 'lat': 4.7448161, 'lon': -74.1070151}, {'name': 'Desconocido', 'lat': 4.6055051, 'lon': -74.1560693}, {'name': 'Desconocido', 'lat': 4.6050589, 'lon': -74.1556926}, {'name': 'GATO AGO-GO', 'lat': 4.6321984, 'lon': -74.0641267}, {'name': 'Malandrines Bar Cafe', 'lat': 4.6327515, 'lon': -74.0682003}, {'name': 'Donde Lucho', 'lat': 4.6295956, 'lon': -74.0686808}, {'name': 'Donde Juancho', 'lat': 4.6296877, 'lon': -74.0686638}, {'name': 'Cigarreria y Cafeteria La 44', 'lat': 4.631933, 'lon': -74.0682733}, {'name': 'El Gran Combo', 'lat': 4.5997473, 'lon': -74.1552916}, {'name': 'Dulce tentación', 'lat': 4.6252952, 'lon': -74.0679633}, {'name': 'Bocado de Reina', 'lat': 4.6298759, 'lon': -74.0669611}, {'name': 'La 37', 'lat': 4.6250807, 'lon': -74.0680021}, {'name': 'Dulce jesus mio', 'lat': 4.6259363, 'lon': -74.0677711}, {'name': 'Kaldivia cafe', 'lat': 4.6259517, 'lon': -74.0678301}, {'name': 'Desconocido', 'lat': 4.6335557, 'lon': -74.179555}, {'name': 'Desconocido', 'lat': 4.7506017, 'lon': -74.0504191}, {'name': 'Ana Isabel', 'lat': 4.7570845, 'lon': -74.1027679}, {'name': 'Estacion Café 13', 'lat': 4.6262393, 'lon': -74.0671261}, {'name': 'Nudols', 'lat': 4.6269134, 'lon': -74.0669859}, {'name': 'Bonmarco', 'lat': 4.5872115, 'lon': -74.1036871}, {'name': 'Cigarreria Emannuel', 'lat': 4.5877433, 'lon': -74.1032981}, {'name': 'Obleas Don Angel', 'lat': 4.5878221, 'lon': -74.1034094}, {'name': 'Bonmarco', 'lat': 4.5883428, 'lon': -74.1032659}, {'name': 'Desconocido', 'lat': 4.5875709, 'lon': -74.1043783}, {'name': 'Desconocido', 'lat': 4.5860278, 'lon': -74.1051145}, {'name': 'Cigarreria Cava Express', 'lat': 4.7574444, 'lon': -74.0487947}, {'name': 'Panadería', 'lat': 4.7527271, 'lon': -74.0983559}, {'name': 'Cafeteria', 'lat': 4.597574, 'lon': -74.1355151}, {'name': 'Delicias del Valle', 'lat': 4.6187302, 'lon': -74.1692602}, {'name': 'Las Delicias', 'lat': 4.6752976, 'lon': -74.0964508}, {'name': 'El Merendero', 'lat': 4.6755622, 'lon': -74.0967563}, {'name': 'Los Nogales', 'lat': 4.6765643, 'lon': -74.0965632}, {'name': "Lorent's", 'lat': 4.6765925, 'lon': -74.0961486}, {'name': 'Coffee Room', 'lat': 4.724779, 'lon': -74.0493719}, {'name': 'Dubai Express', 'lat': 4.6322182, 'lon': -74.0784073}, {'name': 'Auto servicio Express', 'lat': 4.6211981, 'lon': -74.1229036}, {'name': 'Desconocido', 'lat': 4.6381152, 'lon': -74.1544557}, {'name': 'Desconocido', 'lat': 4.600206, 'lon': -74.0757676}, {'name': 'Panadería de la cuarta', 'lat': 4.5905498, 'lon': -74.0760807}, {'name': 'Desconocido', 'lat': 4.6361997, 'lon': -74.1528934}, {'name': 'Café Cultor', 'lat': 4.6515686, 'lon': -74.0564877}, {'name': 'Dicami', 'lat': 4.6683622, 'lon': -74.079949}, {'name': 'Romannoti', 'lat': 4.5945042, 'lon': -74.1391608}, {'name': 'Taty', 'lat': 4.5942935, 'lon': -74.1381528}, {'name': 'Local 2', 'lat': 4.6325004, 'lon': -74.0664806}, {'name': 'Desconocido', 'lat': 4.6324986, 'lon': -74.066851}, {'name': 'Cigarreria el triunfo', 'lat': 4.5934099, 'lon': -74.1386269}, {'name': 'Café Express de la "U"', 'lat': 4.5926295, 'lon': -74.1387449}, {'name': 'Cigarrería Chucuri', 'lat': 4.5925159, 'lon': -74.1387678}, {'name': 'El changaro de chente', 'lat': 4.5926103, 'lon': -74.1392393}, {'name': 'Panadería y cafetería el gran punto.', 'lat': 4.7128596, 'lon': -74.1153944}, {'name': 'Café OMA', 'lat': 4.6835932, 'lon': -74.059973}, {'name': 'MINOS', 'lat': 4.6316591, 'lon': -74.0646372}, {'name': 'batidos de la sabana', 'lat': 4.6316207, 'lon': -74.0645317}, {'name': 'Fruti Lili', 'lat': 4.5925534, 'lon': -74.1383619}, {'name': 'Tienda de Café', 'lat': 4.593201, 'lon': -74.1382665}, {'name': 'COFFEE & CO', 'lat': 4.5930242, 'lon': -74.1382969}, {'name': 'Aqui toy', 'lat': 4.7340459, 'lon': -74.1004899}, {'name': 'Filisias', 'lat': 4.7341646, 'lon': -74.1004635}, {'name': 'kaaba', 'lat': 4.6392016, 'lon': -74.0650822}, {'name': 'COFFE BREAK 52', 'lat': 4.6391268, 'lon': -74.0649181}, {'name': 'Desconocido', 'lat': 4.5951269, 'lon': -74.1339722}, {'name': 'Nicol', 'lat': 4.6398574, 'lon': -74.0685719}, {'name': 'Frutería heladería y cafetería, BANANA SPLIT.', 'lat': 4.7108442, 'lon': -74.1156502}, {'name': 'Desconocido', 'lat': 4.7533223, 'lon': -74.0978571}, {'name': 'Fruta y Café Express', 'lat': 4.6387242, 'lon': -74.0675804}, {'name': 'la 53', 'lat': 4.6404191, 'lon': -74.0671304}, {'name': 'dizzy food, coffe & drinks', 'lat': 4.6324358, 'lon': -74.0648754}, {'name': 'La empanada caldense', 'lat': 4.6384796, 'lon': -74.0663605}, {'name': 'Salón De Onces Marly', 'lat': 4.6355721, 'lon': -74.0659972}, {'name': 'mile y pao', 'lat': 4.5708469, 'lon': -74.0988488}, {'name': 'expresss', 'lat': 4.5696754, 'lon': -74.1003686}, {'name': 'Cafe Pop', 'lat': 4.6403857, 'lon': -74.0627725}, {'name': 'Panes y paneciilos', 'lat': 4.6538892, 'lon': -74.1093082}, {'name': 'barbacoas', 'lat': 4.6540899, 'lon': -74.1094041}, {'name': 'Cafetería', 'lat': 4.6304103, 'lon': -74.1783116}, {'name': 'monalisa', 'lat': 4.7370639, 'lon': -74.0847635}, {'name': 'Nicanor', 'lat': 4.6319283, 'lon': -74.0831512}, {'name': 'Desconocido', 'lat': 4.6815781, 'lon': -74.150919}, {'name': 'Panissimo', 'lat': 4.704861, 'lon': -74.0711828}, {'name': 'Panadería Gurus', 'lat': 4.6737826, 'lon': -74.1085887}, {'name': 'Café LATINO', 'lat': 4.7140155, 'lon': -74.0979986}, {'name': 'Orígenes Café', 'lat': 4.5960741, 'lon': -74.0717528}, {'name': 'Duocafe', 'lat': 4.6493986, 'lon': -74.0607988}, {'name': 'Del Quindio Tienda Cafe', 'lat': 4.6493414, 'lon': -74.0606357}, {'name': 'Cafe Arbol', 'lat': 4.6492993, 'lon': -74.06106}, {'name': 'Starbucks', 'lat': 4.6515047, 'lon': -74.0589342}, {'name': 'Juan Valdez Café', 'lat': 4.686063, 'lon': -74.0568485}, {'name': 'Obleas Dany', 'lat': 4.7142607, 'lon': -74.0704255}, {'name': 'Starbucks', 'lat': 4.6953136, 'lon': -74.0313002}, {'name': 'Camino Del Cafe', 'lat': 4.6945584, 'lon': -74.0315721}, {'name': 'Express way', 'lat': 4.6346923, 'lon': -74.0675419}, {'name': 'Desconocido', 'lat': 4.6283589, 'lon': -74.0779654}, {'name': 'Tostao’', 'lat': 4.6288915, 'lon': -74.078121}, {'name': 'Desconocido', 'lat': 4.634649, 'lon': -74.0677787}, {'name': 'Kafeto', 'lat': 4.6344681, 'lon': -74.067001}, {'name': 'Tropicalisimo', 'lat': 4.6345492, 'lon': -74.0670691}, {'name': 'Conect A-2', 'lat': 4.6342428, 'lon': -74.0663521}, {'name': 'Juan Valdez Café', 'lat': 4.7301021, 'lon': -74.0325316}, {'name': 'Cafetería Esquina Huilense', 'lat': 4.63612, 'lon': -74.0656296}, {'name': 'Cafeteria La Mochila', 'lat': 4.6360988, 'lon': -74.0653813}, {'name': 'Cafatería Sambitto', 'lat': 4.6361175, 'lon': -74.0654627}, {'name': 'Buñuelos', 'lat': 4.6361328, 'lon': -74.0655658}, {'name': 'Antojitos de la 51', 'lat': 4.6383378, 'lon': -74.06585}, {'name': 'Cafeteria Pizzeria', 'lat': 4.6383598, 'lon': -74.0660616}, {'name': 'Fruteria y cafeteria', 'lat': 4.6294449, 'lon': -74.0670157}, {'name': 'Bralir', 'lat': 4.637347, 'lon': -74.0658013}, {'name': 'BUS1 19', 'lat': 4.6391535, 'lon': -74.0649713}, {'name': 'ANDREA', 'lat': 4.6391681, 'lon': -74.0654716}, {'name': 'portal de santa fe', 'lat': 4.5668363, 'lon': -74.0953616}, {'name': 'Desconocido', 'lat': 4.5656201, 'lon': -74.0942369}, {'name': 'Desconocido', 'lat': 4.7446962, 'lon': -74.092744}, {'name': 'Desconocido', 'lat': 4.744936, 'lon': -74.0928218}, {'name': 'heladería de la 46', 'lat': 4.6328352, 'lon': -74.0645494}, {'name': 'Jireh', 'lat': 4.6330365, 'lon': -74.0663722}, {'name': 'Desconocido', 'lat': 4.6320629, 'lon': -74.0665775}, {'name': 'Desconocido', 'lat': 4.6290452, 'lon': -74.0783985}, {'name': 'Desconocido', 'lat': 4.6280202, 'lon': -74.0787284}, {'name': 'GUS® fruterias', 'lat': 4.6288266, 'lon': -74.0671163}, {'name': 'Desconocido', 'lat': 4.753927, 'lon': -74.0807833}, {'name': 'Desconocido', 'lat': 4.7548514, 'lon': -74.0803056}, {'name': 'Desconocido', 'lat': 4.754406, 'lon': -74.0812152}, {'name': 'Rico Ricoto', 'lat': 4.6382579, 'lon': -74.066134}, {'name': 'Desconocido', 'lat': 4.6382211, 'lon': -74.065902}, {'name': 'Fruity Cream', 'lat': 4.6385255, 'lon': -74.0663532}, {'name': 'Fruteria Y Cafeteria', 'lat': 4.6381022, 'lon': -74.0655624}, {'name': 'Felipa', 'lat': 4.6379798, 'lon': -74.0650518}, {'name': 'Cafeteria La Especial', 'lat': 4.6026972, 'lon': -74.1498444}, {'name': 'Cafeteria Leona', 'lat': 4.6030868, 'lon': -74.1504392}, {'name': 'Lo mejor del huila', 'lat': 4.6031384, 'lon': -74.1506259}, {'name': 'Tostao’', 'lat': 4.6330181, 'lon': -74.0653424}, {'name': 'Panadería y cafetería La 10', 'lat': 4.595543, 'lon': -74.0728545}, {'name': 'Café Ibañez', 'lat': 4.5953153, 'lon': -74.0728204}, {'name': 'DELIKATESES DE LA CARRERA 13', 'lat': 4.6283899, 'lon': -74.0671793}, {'name': 'Café Niebla', 'lat': 4.6299011, 'lon': -74.0655139}, {'name': 'almojabaneria EL BUEN SABOR', 'lat': 4.6377066, 'lon': -74.1407313}, {'name': 'Juice Garden', 'lat': 4.6302785, 'lon': -74.0648418}, {'name': 'Sevillana Café', 'lat': 4.748026, 'lon': -74.0990956}, {'name': 'Starbucks', 'lat': 4.6770223, 'lon': -74.049256}, {'name': 'Cigarreria Jerico', 'lat': 4.6372588, 'lon': -74.0660655}, {'name': 'Moreno Brand', 'lat': 4.633351, 'lon': -74.0876824}, {'name': 'Panadería Don Pan', 'lat': 4.7478424, 'lon': -74.0851434}, {'name': 'Panadería Yiyo', 'lat': 4.7118091, 'lon': -74.1026517}, {'name': 'Café OMA', 'lat': 4.6960954, 'lon': -74.0315868}, {'name': 'Juan Valdez Café', 'lat': 4.6947966, 'lon': -74.0311567}, {'name': 'Café el Altillo', 'lat': 4.6959545, 'lon': -74.0297759}, {'name': 'ArtTé', 'lat': 4.6959329, 'lon': -74.0297182}, {'name': 'Café OMA', 'lat': 4.6478065, 'lon': -74.0639966}, {'name': 'Café OMA', 'lat': 4.7038776, 'lon': -74.0429603}, {'name': 'Juan Valdez Café', 'lat': 4.5978475, 'lon': -74.0742431}, {'name': 'El Templo Té', 'lat': 4.6271831, 'lon': -74.0750166}, {'name': 'Juan Valdez Café', 'lat': 4.7153669, 'lon': -74.0292532}, {'name': 'Illy', 'lat': 4.7013359, 'lon': -74.0417743}, {'name': 'Juan Valdez Café', 'lat': 4.7030842, 'lon': -74.0416697}, {'name': 'Starbucks', 'lat': 4.6806941, 'lon': -74.0405438}, {'name': 'Desconocido', 'lat': 4.6570612, 'lon': -74.0563883}, {'name': 'deli', 'lat': 4.6570194, 'lon': -74.0564433}, {'name': 'Desconocido', 'lat': 4.6574886, 'lon': -74.0580173}, {'name': 'Desconocido', 'lat': 4.6435553, 'lon': -74.0628234}, {'name': 'Arte y Pasión Café', 'lat': 4.5981005, 'lon': -74.0771956}, {'name': "Helados Mimo's", 'lat': 4.7158849, 'lon': -74.0293232}, {'name': 'Desconocido', 'lat': 4.6556058, 'lon': -74.0560065}, {'name': 'Desconocido', 'lat': 4.6528486, 'lon': -74.0589628}, {'name': 'Café OMA', 'lat': 4.698468, 'lon': -74.0546938}, {'name': 'Desconocido', 'lat': 4.6360189, 'lon': -74.1388164}, {'name': 'Cafe de la Fonda', 'lat': 4.6182702, 'lon': -74.0781672}, {'name': 'La Castana Empanadas', 'lat': 4.6422611, 'lon': -74.0612832}, {'name': 'Cafe Rec', 'lat': 4.5945627, 'lon': -74.0761754}, {'name': 'Tostao’', 'lat': 4.6395841, 'lon': -74.0744159}, {'name': 'Tostao’', 'lat': 4.6353086, 'lon': -74.0636118}, {'name': 'Juan Valdez Café', 'lat': 4.6065659, 'lon': -74.0711316}, {'name': 'Cafe Casu', 'lat': 4.5964081, 'lon': -74.0703876}, {'name': 'Magola Buendia', 'lat': 4.6014293, 'lon': -74.0678215}, {'name': 'Desconocido', 'lat': 4.7018133, 'lon': -74.0639336}, {'name': 'Cafeteria Ed. Baron', 'lat': 4.6266951, 'lon': -74.0638158}, {'name': 'Social Coffee House', 'lat': 4.6499666, 'lon': -74.0569451}, {'name': 'Salva Patria', 'lat': 4.6404355, 'lon': -74.0607708}, {'name': 'Amor Perfecto', 'lat': 4.6490139, 'lon': -74.0554381}, {'name': 'Casa Rosa', 'lat': 4.6433205, 'lon': -74.061229}, {'name': 'Tostao’', 'lat': 4.6453361, 'lon': -74.0630214}, {'name': 'Contraste Coffee Lab', 'lat': 4.6010593, 'lon': -74.0706847}, {'name': 'The Corner', 'lat': 4.5976135, 'lon': -74.0721845}, {'name': 'Cafe imperial', 'lat': 4.7470672, 'lon': -74.0974336}, {'name': 'cafeteria amiga', 'lat': 4.6442925, 'lon': -74.0792736}, {'name': 'Bourbon coffee Roasters', 'lat': 4.6571425, 'lon': -74.0617672}, {'name': 'Starbucks', 'lat': 4.6029553, 'lon': -74.067186}, {'name': 'Embajada de la Coca Express', 'lat': 4.5993247, 'lon': -74.0696767}, {'name': 'Quipile Coffee Roastery', 'lat': 4.5979417, 'lon': -74.0686638}, {'name': 'Afternoon Tea', 'lat': 4.6801656, 'lon': -74.05028}, {'name': 'Azahar Café', 'lat': 4.6780034, 'lon': -74.0501016}, {'name': 'El señor de las aromáticas', 'lat': 4.6286158, 'lon': -74.0649545}, {'name': 'Café Miró', 'lat': 4.6272428, 'lon': -74.0677122}, {'name': 'Café toscana', 'lat': 4.616045, 'lon': -74.0886232}, {'name': 'Desconocido', 'lat': 4.6143126, 'lon': -74.0888753}, {'name': 'Le bistrot', 'lat': 4.6228935, 'lon': -74.0899032

In [ ]:
# Convertir a GeoDataFrame
df_cafeterias = pd.DataFrame(cafeterias)
df_cafeterias.tail()

                  name       lat        lon
1165            Nómada  4.653276 -74.060031
1166             Calma  4.655056 -74.059587
1167     Amor Perfecto  4.601385 -74.072388
1168  Café del Mercado  4.598387 -74.068614
1169         Muzo Café  4.596449 -74.072670

In [ ]:
gdf_cafeterias = gpd.GeoDataFrame(df_cafeterias,
                                  geometry=gpd.points_from_xy(df_cafeterias.lon, df_cafeterias.lat),
                                  crs="EPSG:4326")
gdf_cafeterias.tail()

                  name       lat        lon                   geometry
1165            Nómada  4.653276 -74.060031  POINT (-74.06003 4.65328)
1166             Calma  4.655056 -74.059587  POINT (-74.05959 4.65506)
1167     Amor Perfecto  4.601385 -74.072388  POINT (-74.07239 4.60139)
1168  Café del Mercado  4.598387 -74.068614  POINT (-74.06861 4.59839)
1169         Muzo Café  4.596449 -74.072670  POINT (-74.07267 4.59645)

In [ ]:
# Integrar los datos en un mismo mapa

# Agregar cafeterías (azul)
for idx, row in gdf_cafeterias.iterrows():
    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=row["name"],
        icon=folium.Icon(color="blue", icon="coffee"),
    ).add_to(m)

# Mostrar mapa
m

 Explicación del Código:

1. Extraemos las cafeterías de la misma forma en la que obtuvimos la información relacionada a los hospitales.
2. Se agregan marcadores en el mapa con diferentes colores:

🔴 Hospitales → rojo
🔵 Cafeterías → azul

In [ ]:
#Descarga esta visualización en un archivo de formato .html
m.save("mapa_bogota.html")
from google.colab import files
files.download("mapa_bogota.html")

###5. Conclusión y Cierre

¿Qué aprendimos en esta clase?

1. Cómo usar APIs geoespaciales para obtener datos de OpenStreetMap.
C2. ómo transformar datos en GeoDataFrames con GeoPandas.
3. Cómo crear mapas interactivos con Folium.